# Codex entries: (id, name, category, description, [chapter roman numerals where covered])
# Categories: CH = Characters & Beings, PF = Peoples & Factions, PL = Places & Realms,
#             AR = Artifacts & Substances, EV = Events & Terms

CATS = [("CH", "Characters &amp; Beings"), ("PF", "Peoples &amp; Factions"),
        ("PL", "Places &amp; Realms"), ("AR", "Artifacts &amp; Substances"),
        ("EV", "Events &amp; Terms")]

CODEX = [
# ---------- Characters & Beings ----------
("aegwynn", "Aegwynn", "CH", "One of the mightiest Guardians of Tirisfal. Struck down an avatar of Sargeras, unaware his spirit escaped into her unborn son, Medivh.", ["V"]),
("alexstrasza", "Alexstrasza the Life-Binder", "CH", "Aspect of the red dragonflight and queen of all dragonkind, charged with the protection of all life. Rendered mortal after the Dragon Soul was used against Deathwing; leads the return to the Dragon Isles.", ["III", "X", "XI", "XIV"]),
("amanthul", "Aman'Thul", "CH", "Highfather of the titan Pantheon. Personally tore the Old God Y'Shaarj out of Azeroth's crust — the wound became the Well of Eternity.", ["I", "II"]),
("anduin", "Anduin Wrynn", "CH", "Varian's gentle, peace-seeking son; king of Stormwind from Legion onward. Dominated and weaponized by the Jailer in Shadowlands; abdicated his throne to wander after his release.", ["XII", "XIII"]),
("archimonde", "Archimonde the Defiler", "CH", "Eredar co-lieutenant of the Burning Legion. Summoned into Azeroth in the Third War and destroyed at the Battle of Mount Hyjal; his alternate-timeline self fell on Draenor.", ["I", "VI", "VIII", "XII"]),
("arthas", "Arthas Menethil", "CH", "Crown prince and paladin of Lordaeron whose step-by-step fall — Stratholme, Frostmourne, patricide — ended with him merging with the Lich King. Slain atop Icecrown Citadel.", ["VIII", "X"]),
("azshara", "Queen Azshara", "CH", "Night elf queen whose bargain with Sargeras brought the first Legion invasion. Remade by N'Zoth into empress of the naga; engineered his release ten thousand years later.", ["IV", "XIII"]),
("bolvar", "Bolvar Fordragon", "CH", "Alliance hero kept alive by dragonfire, who took the Helm of Domination after Arthas fell to serve as warden Lich King — until Sylvanas shattered the Helm.", ["X", "XIII"]),
("cenarius", "Cenarius", "CH", "Demigod of the wild, patron of druidism, teacher of Malfurion. Fought in the War of the Ancients; slain by a demon-blooded Grommash Hellscream in the Third War.", ["IV", "VIII"]),
("cthun", "C'Thun", "CH", "Old God imprisoned beneath the desert of Silithus. Stirred in the vanilla era and was put down inside its temple-prison of Ahn'Qiraj.", ["II", "IX"]),
("ebyssian", "Ebyssian", "CH", "An uncorrupted black dragon raised in secret by tauren. A reluctant third voice in the black dragonflight's succession beside Wrathion and Sabellian.", ["XIV"]),
("fyrakk", "Fyrakk the Blazing", "CH", "Primal Incarnate of fire — the most openly destructive of the four. Imprisoned in the Vault of the Incarnates at the end of the War of the Scaleborn.", ["III", "XIV"]),
("galakrond", "Galakrond", "CH", "A monstrous proto-dragon who devoured his own kind and raised the dead. His defeat by five proto-dragons, aided by Keeper Tyr, led to the creation of the Dragon Aspects.", ["III"]),
("garrosh", "Garrosh Hellscream", "CH", "Grommash's son and Thrall's disastrous successor as warchief. Bombed Theramore, unleashed the heart of Y'Shaarj, was deposed at the Siege of Orgrimmar, and died in a stolen timeline.", ["XI", "XII"]),
("grommash", "Grommash Hellscream", "CH", "Chieftain of the Warsong clan; first orc to drink Mannoroth's blood, and the one who redeemed that sin by dying to kill Mannoroth, freeing his people of the blood-curse.", ["VI", "VIII"]),
("guldan", "Gul'dan", "CH", "The warlock architect of the orcs' corruption; opened the Dark Portal with the possessed Medivh and died grasping for power in a sunken tomb. His alternate-timeline self summoned the Legion's final invasion.", ["VI", "VII", "XII"]),
("guardian", "Guardian of Tirisfal", "CH", "A secret lineage of single champions empowered by a council of magi to fight the Legion's agents on Azeroth. The last Guardian was Medivh.", ["V"]),
("illidan", "Illidan Stormrage", "CH", "Malfurion's twin: gifted, envious, imprisoned ten thousand years for recreating a Well of Eternity. Ruled Outland, fell at the Black Temple, and returned in Legion as the war's ruthless prophet.", ["IV", "VIII", "IX", "XII"]),
("iridikron", "Iridikron the Stonescaled", "CH", "Primal Incarnate of earth — the coldest and most strategic of the four, willing to strike dark bargains to keep the cause alive. Imprisoned in the Vault of the Incarnates.", ["III", "XIV"]),
("jaina", "Jaina Proudmoore", "CH", "Archmage of Dalaran and daughter of Kul Tiras; Arthas's former love who refused to follow him into Stratholme. A lifelong voice for peace repeatedly scarred by war.", ["VIII", "XI"]),
("kaelthas", "Kael'thas Sunstrider", "CH", "Prince of the blood elves who sought salvation for his people's magic-addiction and sold them to the Legion instead. Fell at Tempest Keep, then finally at the Sunwell he tried to defile.", ["VIII", "IX"]),
("kalecgos", "Kalecgos", "CH", "Malygos's successor as leader of the shattered blue dragonflight — a scholar leading a nearly extinct flight.", ["XI", "XIV"]),
("kelthuzad", "Kel'Thuzad", "CH", "Fallen archmage who founded the Cult of the Damned and spread the plague of undeath; raised as a lich in the defiled Sunwell. His necropolis Naxxramas was cast down twice.", ["VIII", "IX"]),
("khadgar", "Khadgar", "CH", "Medivh's apprentice, aged to an old man's body in the battle that killed his master. One of Azeroth's greatest living mages and a fixture of every later war.", ["V", "VII", "XII"]),
("kiljaeden", "Kil'jaeden the Deceiver", "CH", "Eredar lieutenant of Sargeras and architect of the orcs' corruption and the Lich King's creation. Repelled at the Sunwell; finally slain aboard his command ship in Legion.", ["I", "VI", "VII", "IX", "XII"]),
("lich-king", "The Lich King", "CH", "A throne, a helm, and a will: the entity created from Ner'zhul's spirit to raise the Scourge. Successively Ner'zhul, Arthas-merged-with-Ner'zhul, then the warden Bolvar.", ["VII", "VIII", "X", "XIII"]),
("lothar", "Anduin Lothar", "CH", "Champion of Stormwind, called the Lion of Azeroth; led the refugees north after the First War and the Alliance armies in the Second, falling in its final campaign.", ["V", "VII"]),
("malfurion", "Malfurion Stormrage", "CH", "First and greatest of the night elf druids, student of Cenarius, husband of Tyrande. Led the resistance in the War of the Ancients and imprisoned his own twin, Illidan.", ["IV", "VIII"]),
("malygos", "Malygos the Spell-Weaver", "CH", "Aspect of magic, driven half-mad when Deathwing annihilated his flight. After his healing, he judged mortal spellcasting a plague and waged the Nexus War to end it — the first Aspect to die.", ["III", "IV", "X"]),
("mannoroth", "Mannoroth", "CH", "The demon lord whose blood bound the orcs to the Legion. Slain by Grommash Hellscream, breaking the blood-curse.", ["VI", "VIII"]),
("medivh", "Medivh", "CH", "The last Guardian of Tirisfal, possessed from before birth by Sargeras; co-opened the Dark Portal, was slain by his friends — and returned as the prophet who arranged the alliance at Mount Hyjal.", ["V", "VI", "VII", "VIII"]),
("merithra", "Merithra", "CH", "Daughter of Ysera, left to lead the green dragonflight after her mother's death in the Legion invasion.", ["XII", "XIV"]),
("murozond", "Murozond", "CH", "The corrupted future self Nozdormu is prophesied to become — leader of the Infinite dragonflight and the end of the true timeline. Nozdormu guards time knowing how his own story ends.", ["XIV"]),
("neltharion", "Neltharion / Deathwing", "CH", "Aspect of earth, the Earth-Warder — corrupted across millennia by the Old Gods he was set to guard. Betrayed dragonkind in the War of the Ancients as Deathwing; broke the world in the Cataclysm; unmade by the Dragon Soul.", ["III", "IV", "XI"]),
("nerzhul", "Ner'zhul", "CH", "Elder shaman of the orcs, deceived and supplanted by Gul'dan; destroyed Draenor with his portals; remade by Kil'jaeden into the first Lich King.", ["VI", "VII"]),
("nozdormu", "Nozdormu the Timeless One", "CH", "Aspect of the bronze dragonflight and warden of time — burdened with foreknowledge of his own eventual fall into becoming Murozond.", ["III", "XI", "XIV"]),
("nzoth", "N'Zoth", "CH", "The most patient Old God: maker of the naga, corruptor of Deathwing, whisperer behind ten thousand years of schemes. Freed by Azshara's design and destroyed at Ny'alotha — the last of the four.", ["II", "IV", "XIII"]),
("odyn", "Odyn", "CH", "Prime keeper of the titan-forged, who opposed empowering the Dragon Aspects — believing only titan-forged worthy of guarding the world — and founded his own hall of storm-warriors instead.", ["II", "III"]),
("raszageth", "Raszageth the Storm-Eater", "CH", "Primal Incarnate of storm; struck the first blow of the War of the Scaleborn and shattered the dracthyr's Oathbinder. Imprisoned separately in the Froststone Vault — and the first Incarnate freed.", ["III", "XIV"]),
("sabellian", "Sabellian", "CH", "Deathwing's elder son, who guarded his brood on Outland for decades free of the Old Gods' whispers. Rival claimant to the black dragonflight's leadership against Wrathion.", ["XIV"]),
("sargeras", "Sargeras", "CH", "The fallen champion of the Pantheon who concluded all life must burn before the Void could claim it, and forged the Burning Legion. Imprisoned by the restored Pantheon — after driving his sword into Azeroth.", ["I", "IV", "V", "VI", "XII"]),
("sylvanas", "Sylvanas Windrunner", "CH", "Ranger-general of Quel'Thalas, murdered and enslaved as a banshee by Arthas; founder of the Forsaken; warchief who burned Teldrassil; the Jailer's ally and final betrayer, sentenced to redeem the souls of the Maw.", ["VIII", "X", "XII", "XIII"]),
("thrall", "Thrall", "CH", "Son of Durotan, raised a slave, who freed the orcs and rebuilt an honorable Horde on shamanism. Later gave up the warchief's mantle and channeled the Aspects' power to destroy Deathwing.", ["VII", "VIII", "IX", "XI", "XII"]),
("turalyon", "Turalyon", "CH", "Lothar's lieutenant who broke the Horde at the Second War's end, then vanished for a thousand years of Light-forged war beyond the stars before returning in Legion.", ["VII"]),
("tyr", "Tyr", "CH", "Keeper and greatest warrior of the titan-forged; lost his hand to Galakrond and championed the elevation of the five proto-dragons into Aspects.", ["II", "III"]),
("tyrande", "Tyrande Whisperwind", "CH", "High Priestess of the moon goddess Elune and leader of the night elves through every war since the Sundering; forced to mercy-kill the corrupted Ysera.", ["IV", "VIII", "XII"]),
("uther", "Uther the Lightbringer", "CH", "First paladin of the Silver Hand and Arthas's mentor, who refused the Culling of Stratholme and was later murdered by his fallen student.", ["VIII"]),
("varian", "Varian Wrynn", "CH", "King of Stormwind — a child refugee of the First War who grew into the Alliance's warrior-king, and died holding the line at the Broken Shore.", ["VII", "IX", "XI", "XII"]),
("vashj", "Lady Vashj", "CH", "Once a handmaiden of Azshara, remade as a naga sea-witch; Illidan's lieutenant, slain in her reservoir-fortress in Outland.", ["VIII", "IX"]),
("velen", "Velen", "CH", "The Prophet of the draenei, who refused Sargeras's bargain his two closest friends accepted, and led his people's flight across the stars for twenty-five thousand years.", ["VI", "IX"]),
("voljin", "Vol'jin", "CH", "Shadow hunter and chieftain of the Darkspear trolls; led the rebellion against Garrosh and became warchief, only to fall at the Broken Shore — naming Sylvanas with his dying breath.", ["XI", "XII"]),
("vyranoth", "Vyranoth the Frozenheart", "CH", "Primal Incarnate of frost, once Alexstrasza's dear friend — the last and most reluctant to join the Incarnates' war. Imprisoned in the Vault of the Incarnates.", ["III", "XIV"]),
("wrathion", "Wrathion", "CH", "The Black Prince: a young black dragon purified of the Old Gods' corruption before hatching. Brilliant, scheming, and haunted by past misjudgments; claimant to his father Deathwing's flight.", ["XIV"]),
("xavius", "Xavius", "CH", "First of the satyrs, Azshara's counselor turned Legion servant, who corrupted the Emerald Dream into the Nightmare and destroyed Ysera before his end.", ["XII"]),
("yoggsaron", "Yogg-Saron", "CH", "The Old God of death imprisoned beneath Ulduar, who corrupted its keeper-jailers from within. Destroyed in its cell during the Northrend campaign.", ["II", "X"]),
("ysera", "Ysera the Dreamer", "CH", "Aspect of the green dragonflight, bound to the Emerald Dream; Alexstrasza's sister. Corrupted by the Nightmare during the Legion invasion and mercy-killed by Tyrande; her spirit rests in the Dream.", ["III", "XII", "XIV"]),
("yshaarj", "Y'Shaarj", "CH", "Mightiest of the Old Gods, torn from the world by Aman'Thul himself. Its death-wound became the Well of Eternity; its dying breath became the Sha; its heart was sealed away — then dug up.", ["II", "XI"]),
("zovaal", "Zovaal, the Jailer", "CH", "A deposed arbiter of Death, banished to the Maw, who claimed authorship of the Lich King and much else in a plan to rewrite reality. Destroyed at the end of Shadowlands.", ["XIII"]),

# ---------- Peoples & Factions ----------
("alliance", "The Alliance", "PF", "The faction founded as the Alliance of Lordaeron in the Second War; in the modern era led from Stormwind, uniting humans, dwarves, gnomes, night elves, draenei, worgen, and others.", ["VII", "IX"]),
("blood-elves", "High elves / Blood elves", "PF", "Highborne exiles who founded Quel'Thalas and lived on the Sunwell's radiance. After Arthas defiled it, the survivors renamed themselves blood elves (sin'dorei) and later joined the Horde.", ["V", "VIII", "IX"]),
("burning-legion", "The Burning Legion", "PF", "Sargeras's endless demon army, dedicated to burning every world that might host a world-soul. Invaded Azeroth three times; destroyed forever at Argus.", ["I", "IV", "VI", "VIII", "XII"]),
("draenei", "The draenei", "PF", "\"Exiled ones\": the uncorrupted fragment of the eredar who fled Sargeras with Velen, guided by the naaru, and were nearly annihilated by the corrupted orcs on Draenor. Later joined the Alliance.", ["VI", "IX"]),
("dracthyr", "The dracthyr", "PF", "Humanoid dragonkin soldiers created by Neltharion, blending the essences of all five flights. Sealed in stasis after the Oathbinder broke; awake after twenty thousand years as Dragonflight begins.", ["III", "XIV"]),
("dragonflights", "The dragonflights", "PF", "The five ordered kindreds of dragonkind — red (life), green (dream), bronze (time), blue (magic), black (earth) — each led by an Aspect.", ["III", "X", "XI", "XIV"]),
("elemental-lords", "The Elemental Lords", "PF", "The four rulers of Azeroth's primordial elements, enslaved by the Old Gods and banished by the titan-forged. Ragnaros (fire) and Al'Akir (air) returned to serve Deathwing's Cataclysm.", ["II", "IX", "XI"]),
("eredar", "The eredar", "PF", "A brilliant magical civilization of Argus. Most followed Kil'jaeden and Archimonde into the Legion; Velen's refusers became the draenei.", ["I", "VI"]),
("forsaken", "The Forsaken", "PF", "Undead freed from the Lich King's will, forged into a nation by Sylvanas in the ruins of Lordaeron and joined to the Horde.", ["VIII", "X", "XIII"]),
("horde", "The Horde", "PF", "Originally the demon-forged orc war machine; refounded by Thrall on shamanism and honor. In the modern era spans orcs, trolls, tauren, Forsaken, blood elves, and others.", ["VI", "VII", "VIII", "IX", "XI"]),
("mortal-races", "Humans, dwarves &amp; gnomes", "PF", "Descendants of titan-forged servants degraded from stone and metal to flesh by the Old Gods' curse of flesh. Humanity's empire of Arathor and its Seven Kingdoms dominate the Eastern Kingdoms.", ["II", "V"]),
("naaru", "The naaru", "PF", "Benevolent beings of pure Light who guided the draenei's flight from Sargeras. The naaru M'uru's sacrificed heart reignited the Sunwell.", ["I", "VI", "IX"]),
("naga", "The naga", "PF", "Azshara's drowned Highborne court, remade into serpentine sea-dwellers by N'Zoth. Served their queen's schemes for ten thousand years.", ["IV", "VIII", "XIII"]),
("night-elves", "The night elves", "PF", "The kaldorei: the elves of the Well of Eternity, whose empire fell in the Sundering. Turned to druidism and Elune's worship, keeping vigil over the world; their tree-home Teldrassil was burned in the Fourth War.", ["IV", "V", "VIII", "XIII"]),
("old-gods", "The Old Gods", "PF", "Four eldritch parasites hurled at Azeroth by the Void Lords to corrupt the world-soul: Y'Shaarj (slain by Aman'Thul), C'Thun, Yogg-Saron, and N'Zoth — imprisoned, and destroyed one by one across the game's history.", ["I", "II", "IX", "X", "XIII"]),
("orcs", "The orcs", "PF", "Shamanistic clans of Draenor corrupted into the Legion's weapon by Mannoroth's blood; redeemed under Thrall as the core of the new Horde.", ["VI", "VII", "VIII"]),
("pandaren", "The pandaren", "PF", "The people of Pandaria, hidden behind mists since the Sundering, whose culture is built on mastering the emotions that feed the Sha.", ["V", "XI"]),
("primalists", "The Primalists &amp; Incarnates", "PF", "Proto-dragons and elemental zealots who refused the titans' gift, led by the four Primal Incarnates. Defeated in the War of the Scaleborn; their modern cult frees Raszageth on the eve of Dragonflight.", ["III", "XIV"]),
("scourge", "The Scourge", "PF", "The Lich King's undead army, raised by plague to soften Azeroth for the Legion — and dangerous enough to slip that leash.", ["VII", "VIII", "X"]),
("tauren", "The tauren", "PF", "Nomadic bison-folk of Kalimdor's plains, ancient followers of the Earth Mother; among Thrall's first and truest allies in the new Horde.", ["V", "VIII"]),
("titanforged", "The titan-forged &amp; keepers", "PF", "Armies of stone and metal forged by the titans to fight the Black Empire, led by empowered keepers such as Tyr and Odyn. Their cursed descendants became many of the mortal races.", ["I", "II", "III"]),
("titans", "The titans &amp; the Pantheon", "PF", "God-like beings of Order born from world-souls, governed by the Pantheon under Aman'Thul. Shattered by Sargeras's betrayal; their spirits restored at Argus to imprison him.", ["I", "II", "XII"]),
("trolls", "The trolls", "PF", "The Eastern Kingdoms' oldest empires and Kalimdor's ancient tribes; the night elves' own distant ancestors. Their wars against the high elves forged the human-elf alliance.", ["V", "XIII"]),
("void-lords", "The Void Lords", "PF", "Entities of hungering shadow outside reality, whose plan is to corrupt a world-soul into a Dark Titan of the Void. The Old Gods are their weapons.", ["I", "II", "XIII"]),
("wild-gods", "The Wild Gods", "PF", "Great beast-spirits of Life empowered by the keepers — Cenarius's kin among them — tied to the Emerald Dream.", ["II", "IV"]),

# ---------- Places & Realms ----------
("argus", "Argus", "PL", "Homeworld of the eredar, seized by the Legion as its throneworld — and revealed to hold a tortured world-soul used as the Legion's resurrection engine. Site of Sargeras's imprisonment.", ["VI", "XII"]),
("azeroth", "Azeroth", "PL", "The world of the game — and a world-soul: the most powerful unborn titan ever discovered, the true prize behind nearly every war in this chronicle.", ["I", "II", "XII"]),
("black-temple", "The Black Temple", "PL", "A former draenei temple in Outland, seat of Illidan's rule and site of his fall.", ["IX"]),
("dark-portal", "The Dark Portal", "PL", "The gateway torn between Draenor and Azeroth by Gul'dan and the possessed Medivh. Its opening is year zero of the modern calendar.", ["VI", "VII", "IX"]),
("dragon-isles", "The Dragon Isles", "PL", "The dragons' ancient homeland and seat of the Aspects' power, dormant since the flights withdrew — reawakened on the eve of Dragonflight.", ["III", "XIV"]),
("eastern-kingdoms", "The Eastern Kingdoms", "PL", "The eastern continents born of the Sundering: home of the human Seven Kingdoms, Quel'Thalas, Ironforge, and the ruins of Lordaeron.", ["IV", "V"]),
("emerald-dream", "The Emerald Dream", "PL", "The verdant blueprint-realm of Life, tended by the green dragonflight and the druids. Corrupted into the Nightmare during the Legion invasion.", ["I", "III", "XII"]),
("icecrown", "Icecrown Citadel", "PL", "The Lich King's fortress in Northrend, seat of the Frozen Throne — where Arthas fell and where Sylvanas later shattered the Helm of Domination.", ["X", "XIII"]),
("kalimdor", "Kalimdor", "PL", "The western continent born of the Sundering: land of the night elves, tauren, and the Horde's new home of Durotar.", ["IV", "VIII"]),
("lordaeron", "Lordaeron", "PL", "The proudest of the human Seven Kingdoms, destroyed by its own prince in the Third War; its plagued ruins became the Forsaken's Undercity.", ["V", "VII", "VIII", "XIII"]),
("nordrassil", "Nordrassil", "PL", "The World Tree planted over the Well of Eternity's remnant at Mount Hyjal, blessed by three Aspects. Its sacrifice destroyed Archimonde — and cost the night elves their immortality.", ["IV", "VIII"]),
("northrend", "Northrend", "PL", "The frozen crown of the world: the Lich King's domain, Ulduar's resting place, and the battleground of the war against the Scourge.", ["IV", "VII", "X"]),
("orgrimmar", "Orgrimmar", "PL", "The Horde's capital in Durotar, founded by Thrall — and besieged by its own people to depose Garrosh.", ["IX", "XI"]),
("outland", "Draenor / Outland", "PL", "The orcs' and draenei's savage homeworld, shattered by Ner'zhul's portals into the floating ruin called Outland — later ruled by Illidan. An intact alternate-timeline Draenor hosts the Warlords campaign.", ["VI", "VII", "IX", "XII"]),
("pandaria", "Pandaria", "PL", "The mist-hidden southern continent, homeland of the pandaren and resting place of Y'Shaarj's lingering Sha — dragged into the faction war upon its discovery.", ["II", "V", "XI"]),
("quelthalas", "Quel'Thalas", "PL", "The high elves' forest kingdom in the north of the Eastern Kingdoms, built around the Sunwell; carved apart by Arthas in the Third War.", ["V", "VIII"]),
("shadowlands", "The Shadowlands", "PL", "The realm of Death: an afterlife machinery of soul-triage whose realms starved while the Jailer diverted every soul into the torture-pit of the Maw.", ["I", "XIII"]),
("silithus", "Silithus", "PL", "The desert prison-ground of C'Thun — and the place where Sargeras's sword now stands impaled in the world, bleeding Azerite.", ["IX", "XII", "XIII"]),
("stormwind", "Stormwind", "PL", "The southernmost human kingdom: first casualty of the Horde's invasion, rebuilt to become the Alliance's modern capital under the Wrynn kings.", ["V", "VII", "IX"]),
("sunwell", "The Sunwell", "PL", "The fount of power at Quel'Thalas's heart, kindled from the old Well's waters. Defiled by Arthas; reborn through the naaru M'uru's heart as a well of Light and arcane both.", ["V", "VIII", "IX"]),
("teldrassil", "Teldrassil", "PL", "The second World Tree, grown as the night elves' island home — burned with its civilians by Sylvanas's order at the start of the Fourth War.", ["XIII"]),
("ulduar", "Ulduar", "PL", "The titan machine-city in Northrend built to watch Yogg-Saron's prison — whose jailers the Old God corrupted from within.", ["II", "X"]),
("vault-incarnates", "The Vault of the Incarnates", "PL", "The prison built for the defeated Incarnates: sealed by Nozdormu's temporal locks, Malygos's arcane wards, and Neltharion's burial. Raszageth was held separately in the Froststone Vault of the Forbidden Reach.", ["III", "XIV"]),
("well-of-eternity", "The Well of Eternity", "PL", "The becalmed lake of the world-soul's own lifeblood, formed from the wound of Y'Shaarj's removal. Fountainhead of night elf civilization; destroyed in the Sundering — its stolen waters kindled new wells.", ["II", "IV", "V"]),

# ---------- Artifacts & Substances ----------
("azerite", "Azerite", "AR", "The crystallized lifeblood of Azeroth's world-soul, welling from the sword-wound in Silithus — a weaponizable god-blood whose promise ignited the Fourth War.", ["XII", "XIII"]),
("demon-soul", "The Dragon Soul / Demon Soul", "AR", "The golden disc Neltharion forged in secret, holding a portion of every flight's essence except his own. His weapon of betrayal — and, ten thousand years later, the only weapon that could unmake him.", ["IV", "XI"]),
("frostmourne", "Frostmourne", "AR", "The soul-drinking runeblade of the Frozen Throne, taken by Arthas at the cost of his soul. Shattered at Icecrown's summit, releasing the souls it had devoured.", ["VII", "VIII", "X"]),
("heart-yshaarj", "The Heart of Y'Shaarj", "AR", "The sealed heart of the slain Old God, unearthed and awakened by Garrosh Hellscream in Pandaria's sacred vale.", ["II", "XI"]),
("helm", "The Helm of Domination", "AR", "The crown that housed the Lich King's will, worn in turn by Ner'zhul's spirit, Arthas, and Bolvar — until Sylvanas shattered it and tore open the sky.", ["VII", "VIII", "X", "XIII"]),
("sword-sargeras", "The Sword of Sargeras", "AR", "The continent-sized blade Sargeras drove into Silithus as he was imprisoned — a lasting wound in the world-soul, still standing in the desert.", ["XII", "XIII"]),

# ---------- Events & Terms ----------
("aspect", "Aspect", "EV", "One of five dragons empowered by the Pantheon (through the keepers, at Tyr's urging) as guardians of a domain of the world: life, dreams, time, magic, and earth. Their powers were spent destroying Deathwing.", ["III", "XI", "XIV"]),
("curse-of-flesh", "The curse of flesh", "EV", "The Old Gods' disease that softened the titan-forged from stone and metal into mortal flesh — the origin of humans, dwarves, gnomes, and others.", ["II", "V"]),
("sha", "The Sha", "EV", "The lingering breath of dead Y'Shaarj: negative emotion — doubt, despair, anger, fear — given monstrous physical form in Pandaria.", ["II", "XI"]),
("sundering", "The Great Sundering", "EV", "The implosion of the Well of Eternity that ended the War of the Ancients and shattered the one continent into the modern world — the \"before/after\" line of ancient history.", ["IV"]),
("world-soul", "World-soul", "EV", "A planet within which a titan's soul gestates. Azeroth is the most powerful world-soul ever found — which is why everyone cosmic wants her.", ["I", "II", "XII", "XIII"]),
]
