# Chapters VIII-XIV
W = "https://warcraft.wiki.gg/wiki/"

CHAPTERS_B = [
dict(slug="08-third-war", num="VIII", accent="#6fd0d6",
era="Year 20 – 21 after the Portal", title="The Third War",
sub="The plague, the fall of Arthas, the rebirth of the Horde, and the last stand at Mount Hyjal",
sources=[("Third War — Warcraft Wiki", W+"Third_War"), ("Arthas Menethil — Warcraft Wiki", W+"Arthas_Menethil"), ("Culling of Stratholme — Warcraft Wiki", W+"Culling_of_Stratholme"), ("Sylvanas Windrunner — Warcraft Wiki", W+"Sylvanas_Windrunner"), ("Battle of Mount Hyjal — Warcraft Wiki", W+"Battle_of_Mount_Hyjal")],
content="""
<p class="lede">The events of <em>Warcraft III</em> — the single most important stretch of story in the franchise, and the foundation of everything World of Warcraft is. Take this chapter slowly.</p>

<h2>The plague of undeath</h2>
<p>The <a class="cx" href="codex.html#lich-king">Lich King</a> worked exactly as designed. Through a death-cult led by the fallen archmage <a class="cx" href="codex.html#kelthuzad">Kel'Thuzad</a>, plague-tainted grain flowed into the villages of <a class="cx" href="codex.html#lordaeron">Lordaeron</a>, and the dead began to rise. Investigating the outbreak: the kingdom's crown prince <strong><a class="cx" href="codex.html#arthas">Arthas Menethil</a></strong> — a broad-shouldered golden-haired paladin in the silver-and-blue of his kingdom; the realm's golden son, mentored by the great paladin <a class="cx" href="codex.html#uther">Uther the Lightbringer</a>, in love with the young mage <a class="cx" href="codex.html#jaina">Jaina Proudmoore</a>. What follows is the most famous fall in the setting, and it happens step by defensible step.</p>

<h2>The fall of Arthas</h2>
<p>At the city of <a class="cx" href="codex.html#stratholme">Stratholme</a>, Arthas discovered the shipped grain had already been eaten: every citizen was hours from rising as Scourge. His solution — over Uther's horrified refusal and as Jaina turned away — was the <strong>Culling of Stratholme</strong>: kill the city before it turned. From there the descent steepened. He pursued the plague's demon-herald to Northrend; on the ice, obsession swallowed him. Warned that the runeblade <a class="cx" href="codex.html#frostmourne">Frostmourne</a> would cost him his soul, he took it anyway. The blade bound him to the Lich King's will, and the prince sailed home a monster — golden hair gone bone-white, skin corpse-pale, the silver plate of a paladin exchanged for black armor, eyes burning ice-blue: he murdered his father on the throne, killed Uther, and raised Kel'Thuzad as an undead lich. Lordaeron ceased to exist as a nation, its lands rotting into the Plaguelands.</p>
<p>Then Arthas turned east and did the thing the elves have never forgiven. He carved through <a class="cx" href="codex.html#quelthalas">Quel'Thalas</a>, murdered its ranger-general <strong><a class="cx" href="codex.html#sylvanas">Sylvanas Windrunner</a></strong> — a golden-haired elf in forest leathers, her people's finest archer — and, refusing her the dignity of death, tore her spirit out and enslaved it as a banshee in his service. (When she later reclaims a body, it is changed: ashen skin, eyes glowing ember-red under a dark hood — beautiful the way a knife is. That is the Sylvanas every later chapter means.) He defiled the <a class="cx" href="codex.html#sunwell">Sunwell</a> to resurrect Kel'Thuzad, poisoning the fount that fed every high elf's soul. The survivors, led by prince <a class="cx" href="codex.html#kaelthas">Kael'thas Sunstrider</a>, renamed themselves the <strong>sin'dorei</strong> — <a class="cx" href="codex.html#blood-elves">blood elves</a> — in mourning, and began looking for anything to feed the addiction the Sunwell's loss left behind.</p>
<p>The Scourge then annihilated the mage-city of <a class="cx" href="codex.html#dalaran">Dalaran</a>'s defenses and used its books to summon the demon lord <a class="cx" href="codex.html#archimonde">Archimonde</a> into the world. The Legion's third great play for Azeroth had begun — with the Scourge as its plough.</p>

<h2>Meanwhile: the Horde reborn</h2>
<p>In the same years, the slave-gladiator <strong><a class="cx" href="codex.html#thrall">Thrall</a></strong> — a green orc built like a fortress door, with rare storm-blue eyes, in scavenged black plate with the warhammer <a class="cx" href="codex.html#doomhammer">Doomhammer</a> across his back — escaped, found the old Frostwolf exiles, learned the shamanism his people had abandoned, and did the impossible: he broke open the internment camps and woke the orcs from their gray despair — not with demon blood, but with their old faith. Guided by a mysterious prophet (Medivh's redeemed spirit, making amends for his possessed life's work), Thrall led his new Horde across the sea to <a class="cx" href="codex.html#kalimdor">Kalimdor</a>. There they befriended the <a class="cx" href="codex.html#tauren">tauren</a> and collided with the <a class="cx" href="codex.html#night-elves">night elves</a>. The war-chief <a class="cx" href="codex.html#grommash">Grommash Hellscream</a> — wiry and ferocious, his jaw tattooed black, swinging an axe with holes bored through the blade so it screams as it cuts; first to drink the demon's blood a generation before — fell to it again, slew the demigod <a class="cx" href="codex.html#cenarius">Cenarius</a>, and then, in the franchise's great redemption scene, died killing <a class="cx" href="codex.html#mannoroth">Mannoroth</a> himself, breaking the blood-curse on his people forever. "The blood haze has lifted," Thrall is told. The Horde's debt was its own again.</p>

<h2>Mount Hyjal</h2>
<p>Archimonde marched on Mount Hyjal to devour the World Tree <a class="cx" href="codex.html#nordrassil">Nordrassil</a> and the power of the Well beneath it. At Medivh's urging, Jaina's human survivors, Thrall's Horde, and Tyrande and Malfurion's night elves — enemies days earlier — held the slopes together in the setting's defining last stand, buying time until Malfurion sprang his trap: the tree's own spirits detonated against the demon lord. Archimonde was destroyed; the night elves paid with the tree's blessing, and with it their immortality. The Legion was broken for a generation — and the fragile idea of Horde–Alliance coexistence was born on that mountainside.</p>

<h2>Aftershocks</h2>
<p>Three loose threads from these years drive the next decade. <strong>Illidan</strong>, freed from his ten-thousand-year prison, accepted a commission from Kil'jaeden to destroy the weakened Lich King, gathered the naga and Kael'thas's desperate blood elves, and fled to Outland when he failed — half villain, half jilted weapon. <strong>Sylvanas</strong> tore her will free as the Lich King's power flickered, seized the plague-lands of fallen Lordaeron, and forged the free-willed undead into a new people: the <a class="cx" href="codex.html#forsaken">Forsaken</a>, who joined the Horde out of shared outcast pragmatism. And <strong>Arthas</strong>, racing Illidan to the Frozen Throne, shattered the ice, donned the <a class="cx" href="codex.html#helm">Helm of Domination</a>, and fused with Ner'zhul's spirit: the prince and the Lich King became one being. Then he sat upon the Frozen Throne — and for years, the top of the world went silent.</p>
"""),

dict(slug="09-world-at-war", num="IX", accent="#8fce5a",
era="World of Warcraft & The Burning Crusade", title="The World at War",
sub="Old Gods stirring, the reopened Dark Portal, and the fall of Illidan — vanilla WoW and TBC",
sources=[("C'Thun — Warcraft Wiki", W+"C%27Thun"), ("Kael'thas Sunstrider — Warcraft Wiki", W+"Kael%27thas_Sunstrider"), ("Black Temple — Warcraft Wiki", W+"Black_Temple"), ("Sunwell Plateau — Warcraft Wiki", W+"Sunwell_Plateau"), ("M'uru — Warcraft Wiki", W+"M%27uru")],
content="""
<p class="lede">World of Warcraft opens four years after Hyjal. The <a class="cx" href="codex.html#alliance">Alliance</a> (now led from rebuilt <a class="cx" href="codex.html#stormwind">Stormwind</a> under King <a class="cx" href="codex.html#varian">Varian Wrynn</a>) and Thrall's <a class="cx" href="codex.html#horde">Horde</a> (from the new orc capital of <a class="cx" href="codex.html#orgrimmar">Orgrimmar</a>) keep a cold, grudging peace — and adventurers, meaning the players, become the era's real protagonists.</p>

<h2>Vanilla: old evils stir</h2>
<p>The original game's stories are mostly the buried past clawing at the floorboards. Deathwing's scheming children — <a class="cx" href="codex.html#onyxia">Onyxia</a>, secretly whispering in Stormwind's court in human guise, and <a class="cx" href="codex.html#nefarian">Nefarian</a>, breeding abomination-dragons in his volcanic fortress — are hunted down. The Elemental Lord <a class="cx" href="codex.html#ragnaros">Ragnaros</a>, anciently banished beneath the mountains, is destroyed in his Molten Core. In the desert of <a class="cx" href="codex.html#silithus">Silithus</a>, the war against the insectoid servants of the Old God <a class="cx" href="codex.html#cthun">C'Thun</a> reignites, and the god itself — imprisoned since Chapter II, never fully healed — is put down inside its temple-prison of <a class="cx" href="codex.html#ahnqiraj">Ahn'Qiraj</a>. And above the Plaguelands, Kel'Thuzad's floating necropolis <a class="cx" href="codex.html#naxxramas">Naxxramas</a> is cast down. Every one of these is the deep past refusing to stay buried; none of them is the future. That arrives through a portal.</p>

<h2>The Burning Crusade: through the Dark Portal</h2>
<p>The <a class="cx" href="codex.html#dark-portal">Dark Portal</a> reopens, and both factions march into <a class="cx" href="codex.html#outland">Outland</a> — the shattered husk of Draenor from Chapter VII — where <a class="cx" href="codex.html#illidan">Illidan</a> rules from the <a class="cx" href="codex.html#black-temple">Black Temple</a> with his lieutenants: the naga sea-witch Lady <a class="cx" href="codex.html#vashj">Vashj</a> — six arms, a mane of living serpents — and the blood elf prince <a class="cx" href="codex.html#kaelthas">Kael'thas</a>, golden-haired and impossibly poised, three captive green suns orbiting his shoulders. Two great redemption-and-damnation arcs collide here:</p>
<ul>
<li><strong>The draenei return.</strong> Velen's people — the genocide's survivors, some now aboard a stolen dimension-ship that crashes on Azeroth — join the Alliance, bringing the story of Argus and the naaru with them.</li>
<li><strong>Kael'thas falls.</strong> The blood elf prince, promised salvation for his people's magic-addiction, sells them to the Legion instead — even capturing a naaru, <strong><a class="cx" href="codex.html#muru">M'uru</a></strong>, for his people to feed on. The blood elves who stay loyal to their homeland join the Horde; their prince becomes their bitterest enemy.</li>
</ul>
<p>The campaign rolls through Vashj's reservoir-fortress and Kael'thas's Tempest Keep, and finally through the Black Temple itself, where Illidan — betrayer, betrayed, never quite villain enough to hate — falls to the adventurers he sneered at. His last words, "the huntsmaster is worthless," are less famous than his first: <em>"You are not prepared!"</em>, the expansion's tagline and still the most quoted line in the game.</p>

<h2>The Sunwell reborn</h2>
<p>The finale closes the wound of Chapter VIII. A broken Kael'thas drags the dying naaru M'uru to the ruins of the <a class="cx" href="codex.html#sunwell">Sunwell</a> and begins summoning <a class="cx" href="codex.html#kiljaeden">Kil'jaeden</a> bodily into the world through it. The summoning is broken, the Deceiver is hurled back — and in the aftermath, Velen pours the naaru's radiant heart into the defiled fount. The Sunwell reignites, no longer merely arcane but touched by the Light. The blood elves' long grief finally has a dawn — a redemption that becomes the seed of the much later <em>Midnight</em> expansion.</p>
"""),

dict(slug="10-wrath", num="X", accent="#7f9fd9",
era="Wrath of the Lich King", title="The War Against the Lich King",
sub="Northrend, the madness in Ulduar, the Aspect who broke — and the fall of Arthas",
sources=[("War against the Lich King — Warcraft Wiki", W+"War_against_the_Lich_King"), ("Yogg-Saron — Warcraft Wiki", W+"Yogg-Saron"), ("Nexus War — Warcraft Wiki", W+"Nexus_War"), ("Bolvar Fordragon — Warcraft Wiki", W+"Bolvar_Fordragon"), ("Icecrown Citadel — Warcraft Wiki", W+"Icecrown_Citadel")],
content="""
<p class="lede">The silence at the top of the world ends. <a class="cx" href="codex.html#arthas">Arthas</a> wakes, the <a class="cx" href="codex.html#scourge">Scourge</a> attacks every capital at once, and both factions launch full invasions of <a class="cx" href="codex.html#northrend">Northrend</a>. This expansion is the payoff of everything Warcraft III set up, and it's still widely called the peak of the game's early era.</p>

<h2>Three wars in one</h2>
<p><strong>The war against the Scourge</strong> grinds through haunted fjords and plagued tundra toward <a class="cx" href="codex.html#icecrown">Icecrown Citadel</a>. Its darkest hour is the battle at <a class="cx" href="codex.html#wrathgate">Angrathar the Wrathgate</a>, where a renegade Forsaken faction unleashes a new plague on Scourge and living alike — killing Horde and Alliance heroes en masse, nearly shattering the factions' cold peace into open war, and forcing <a class="cx" href="codex.html#sylvanas">Sylvanas</a> to retake her own capital from her mutineers. Trust between (and inside) the factions never fully recovers.</p>
<p><strong>The war under the earth</strong> is the horror movie. Beneath the titan machine-city of <a class="cx" href="codex.html#ulduar">Ulduar</a>, the keepers' ancient wards are found broken from within: the Old God <a class="cx" href="codex.html#yoggsaron">Yogg-Saron</a> — a god that is mostly mouths, a heaving mass of green-black flesh and grins in the dark — imprisoned there since Chapter II, has long since corrupted its own jailers. Adventurers fight through the mind-bent keepers and put the Old God down in its cell — the second of the four Old Gods to be destroyed, and a live demonstration that the titans' prisons are failing.</p>
<p><strong>The Nexus War</strong> is the dragon tragedy. <a class="cx" href="codex.html#malygos">Malygos</a>, Aspect of Magic — driven half-mad ten thousand years earlier when Deathwing annihilated his flight, only recently healed — surveys the reckless magic of mortals and declares a simple verdict: revoke it. His blue flight begins severing the world's arcane arteries and killing mortal spellcasters wholesale. The other dragonflights, led by <a class="cx" href="codex.html#alexstrasza">Alexstrasza</a>, side with the mortals against their own brother. Malygos dies in his own sanctum at mortal and dragon hands — the first Aspect to fall, by the queen's own anguished order. Remember her grief; Dragonflight is built on it.</p>

<h2>The Frozen Throne</h2>
<p>The final assault on Icecrown Citadel — a black metal spire rising from the glacier, visible for miles, warm nowhere — climbs through Arthas's trophy-hall of horrors — including the raised corpse of Sylvanas's own sister-in-arms, and Frostmourne's chamber, where the trapped soul of his father waits. At the summit, the Lich King springs his real plan: he has let the world's champions come to him, intending to raise the strongest of them as his generals. He kills the entire raid — and is undone by mercy planted decades earlier: the spirit of Uther had revealed that a fragment of the good prince might remain, and the paladin <a class="cx" href="codex.html#tirion">Tirion Fordring</a>, frozen and praying, is answered. Frostmourne shatters; the imprisoned souls it drank turn on their captor; and Arthas Menethil dies at last, asking his father's ghost if it is finally over.</p>
<p>It isn't, quite. Without a Lich King, the mindless Scourge would scour the world unchecked — someone must wear the crown. The fallen Alliance hero <a class="cx" href="codex.html#bolvar">Bolvar Fordragon</a>, kept alive-in-torment by dragonfire, takes the <a class="cx" href="codex.html#helm">Helm of Domination</a> and the Frozen Throne as the new, jailer Lich King: not a conqueror but a warden, meant to be forgotten. File that arrangement away — its breaking is Chapter XIII.</p>
"""),

dict(slug="11-cataclysm-mists", num="XI", accent="#e0a23f",
era="Cataclysm & Mists of Pandaria", title="The World Broken, the World Found",
sub="Deathwing shatters Azeroth and the Aspects pay everything to stop him; then a hidden continent pays for the factions' war",
sources=[("Deathwing — Warcraft Wiki", W+"Deathwing"), ("Dragon Soul (raid) — Warcraft Wiki", W+"Dragon_Soul_(instance)"), ("Pandaria — Warcraft Wiki", W+"Pandaria"), ("Sha — Warcraft Wiki", W+"Sha"), ("Garrosh Hellscream — Warcraft Wiki", W+"Garrosh_Hellscream"), ("Siege of Orgrimmar — Warcraft Wiki", W+"Siege_of_Orgrimmar")],
content="""
<p class="lede">Two expansions, one arc: the last Old-God-driven apocalypse of the old world, and the self-inflicted catastrophe that followed it. For Dragonflight, this is the most essential chapter on the site.</p>

<h2>The Cataclysm</h2>
<p>Deep beneath the earth, <a class="cx" href="codex.html#neltharion">Deathwing</a> — his body so ruined and so overfull of magma that it could no longer hold itself together, riveted into plates of elementium armor with molten rock glowing through every seam, his jaw sheathed in metal — erupts through the world's crust, driven by the Old Gods' final design. The event is simply called <strong>the Cataclysm</strong>: coastlines drown, zones burn, the map of the classic world is literally redrawn, and the Elemental Lords <a class="cx" href="codex.html#ragnaros">Ragnaros</a> (restored) and Al'Akir join his <a class="cx" href="codex.html#twilights-hammer">Twilight's Hammer</a> doomsday cult. The Old Gods' plan is explicit now: break the world's order utterly and drown the world-soul in shadow — the "Hour of Twilight."</p>
<p>Against him stand the last four Aspects and an unlikely fifth: <a class="cx" href="codex.html#thrall">Thrall</a>, who has handed the Horde to a new warchief so he can serve the whole world as a shaman. The counterstroke turns on Chapter IV's cursed artifact: <a class="cx" href="codex.html#nozdormu">Nozdormu</a> guides heroes through time to steal the <a class="cx" href="codex.html#demon-soul">Dragon Soul</a> from the past — the one weapon bearing the essence of all flights but Deathwing's own. In the <strong>Dragon Soul</strong> raid, Thrall channels the combined, freely-given power of Alexstrasza, Ysera, Nozdormu, and Malygos's successor <a class="cx" href="codex.html#kalecgos">Kalecgos</a> through the artifact, and Deathwing is unmade above the Maelstrom — the wound of ten thousand years finally closed.</p>
<p>The price is the premise of Dragonflight. In that final channeling, <strong>the Aspects spend the last of their titan-given power and become, in their own word, mortal</strong>. Nozdormu names it the Age of Mortals: the dragons' great charge is fulfilled, their purpose spent, their flights barely able to produce another generation. Quietly, over the following years, dragonkind fades from the world's stage.</p>

<h2>Mists of Pandaria</h2>
<p>With the apocalypse cancelled, the factions immediately resume their favorite pastime. A naval skirmish reveals a continent hidden behind mists since before the Sundering: <a class="cx" href="codex.html#pandaria">Pandaria</a> — jade forests, terraced emerald valleys, cloud-wrapped peaks, a continent like a landscape painting — serene homeland of the <a class="cx" href="codex.html#pandaren">pandaren</a>, black-and-white bear-folk of unhurried good humor. And prison of the <a class="cx" href="codex.html#sha">Sha</a>: the lingering breath of dead Y'Shaarj from Chapter II, ink-dark creatures with pale mask-like faces that condense out of doubt, despair, anger, and fear. Into this landscape of emotional landmines the Horde and Alliance import a war, and the land itself sickens around them. It is the setting's most elegant thesis statement: <em>the faction conflict is not colorful sports rivalry; it is a corruption vector.</em></p>
<p>Its proof is <a class="cx" href="codex.html#garrosh">Garrosh Hellscream</a> — Grommash's son, mahogany-brown like the uncorrupted clans, built like a siege engine, his father's black jaw-tattoo and screaming axe both inherited; Thrall's chosen successor, and a warrior who mistakes cruelty for strength. His escalations run from bombing the Alliance city of Theramore off the map to, at last, digging up the sealed <a class="cx" href="codex.html#heart-yshaarj">heart of Y'Shaarj</a> itself and unleashing it in Pandaria's holiest vale, scarring it perhaps forever. The Horde's own component peoples — trolls under <a class="cx" href="codex.html#voljin">Vol'jin</a>, tauren, blood elves, Forsaken — rise against him, and in the <strong>Siege of Orgrimmar</strong> a joint Horde-Alliance force drags the warchief from his bunker. Vol'jin becomes warchief; Varian, at the peak of his kingship, chooses peace over conquest; and Garrosh is taken away to stand trial for war crimes. He never serves the sentence — which is how the next chapter starts.</p>
"""),

dict(slug="12-warlords-legion", num="XII", accent="#5faf6e",
era="Warlords of Draenor & Legion", title="The Legion's Last Crusade",
sub="A timeline stolen, a demon army's final invasion, the death of a Dreamer — and a sword through the world",
sources=[("Warlords of Draenor — Warcraft Wiki", W+"World_of_Warcraft:_Warlords_of_Draenor"), ("Third invasion of the Burning Legion — Warcraft Wiki", W+"Third_invasion_of_the_Burning_Legion"), ("Argus — Warcraft Wiki", W+"Argus"), ("Sword of Sargeras — Warcraft Wiki", W+"Sword_of_Sargeras"), ("Azerite — Warcraft Wiki", W+"Azerite")],
content="""
<p class="lede">Two expansions that form one story: the Legion's long-promised final invasion — and the wound it leaves in the planet on its way out.</p>

<h2>Warlords of Draenor: the stolen timeline</h2>
<p>Awaiting trial, <a class="cx" href="codex.html#garrosh">Garrosh</a> is broken out by a rogue bronze dragon and escapes somewhere no manhunt can follow: an <em>alternate timeline's</em> <a class="cx" href="codex.html#outland">Draenor</a>, thirty-five years in its past, before the orcs ever drank demon blood. There he arms his father's uncorrupted generation with modern war-machines and forges them into the Iron Horde — a conquering army meant to redo history with the demon's bargain refused and the genocide kept. Azeroth's heroes invade the alternate world to stop him; Garrosh dies in a duel with Thrall; and the campaign's endgame goes to a familiar face, for in every timeline there is a <a class="cx" href="codex.html#guldan">Gul'dan</a>. This one, spurned by his own people, summons the Legion in full — and when alternate-Draenor is saved anyway, Gul'dan is hurled by <a class="cx" href="codex.html#kiljaeden">Kil'jaeden</a> through the timeways into the <em>main</em> universe, with one job: open the door.</p>
<p>The expansion is mechanically beloved and narratively awkward — a time-travel cul-de-sac — but its consequences are enormous: it hands the main timeline the architect of its final Legion war, and later, in Legion's aftermath, it delivers an entire population of uncorrupted orcs (the Mag'har) into the Horde.</p>

<h2>Legion: the third invasion</h2>
<p>Gul'dan raises the Tomb of Sargeras — the sunken vault his prime-timeline self died opening in Chapter VII — and through it the <a class="cx" href="codex.html#burning-legion">Burning Legion</a> invades Azeroth at a scale dwarfing every previous war. The opening battle at the Broken Shore is a massacre of leaders: King <a class="cx" href="codex.html#varian">Varian</a> and Warchief <a class="cx" href="codex.html#voljin">Vol'jin</a> both die, the crown passing to Varian's gentle son <a class="cx" href="codex.html#anduin">Anduin</a> and — fatefully — the warchief's mantle to <a class="cx" href="codex.html#sylvanas">Sylvanas</a>. Adventurers rise as leaders of their class orders, wielding legendary artifact weapons, and the war runs on three great rails:</p>
<ul>
<li><strong>The Emerald Nightmare.</strong> The satyr lord <a class="cx" href="codex.html#xavius">Xavius</a> corrupts the <a class="cx" href="codex.html#emerald-dream">Emerald Dream</a> itself, and <a class="cx" href="codex.html#ysera">Ysera the Dreamer</a> — poisoned, turned against everything she is — must be put down by <a class="cx" href="codex.html#tyrande">Tyrande</a>, the closest thing the setting has to a mercy-killing of a goddess by her own priestess. Her spirit passes into the Dream; her daughter <a class="cx" href="codex.html#merithra">Merithra</a> is left to inherit a grief the size of a flight.</li>
<li><strong>Illidan's return.</strong> The demon hunters resurrect their master, and <a class="cx" href="codex.html#illidan">Illidan</a> — vindicated as the one who always understood what the Legion required — becomes the war's ruthless prophet. Kil'jaeden is finally slain aboard his own command ship, admitting with his dying breath that he had always known Sargeras's bargain was a lie; and Illidan, characteristically, uses the moment to tear open a permanent portal to <a class="cx" href="codex.html#argus">Argus</a>, the Legion's throneworld, hanging it in Azeroth's sky. No more repelling invasions: the war goes to them.</li>
<li><strong>Argus.</strong> On the draenei's lost homeworld — revealed to be a tortured world-soul of its own, its titan-spirit enslaved as the Legion's resurrection engine — the heroes free the spirits of the Pantheon, and <a class="cx" href="codex.html#sargeras">Sargeras</a> himself is finally seized and imprisoned by his restored kin at the seat of the Pantheon.</li>
</ul>

<h2>The sword</h2>
<p>He gets one last swing. As the Pantheon drags him from reality, Sargeras drives his colossal blade into Azeroth — a continent-sized <a class="cx" href="codex.html#sword-sargeras">sword</a> impaling the desert of <a class="cx" href="codex.html#silithus">Silithus</a>, wounding the <a class="cx" href="codex.html#world-soul">world-soul</a> herself. The planet bleeds: her golden lifeblood wells up through the wound as a crystalline substance the dwarves name <a class="cx" href="codex.html#azerite">Azerite</a> — raw, portable, weaponizable god-blood. The Legion is finished forever. The peace lasts exactly as long as it takes both factions to understand what Azerite is worth.</p>
"""),

dict(slug="13-bfa-shadowlands", num="XIII", accent="#d88fb0",
era="Battle for Azeroth & Shadowlands", title="The War, the Whisper, and the Grave",
sub="Teldrassil burns, the last Old God rises, the sky is torn open — and Sylvanas's long story ends in the afterlife",
sources=[("Battle for Azeroth — Warcraft Wiki", W+"World_of_Warcraft:_Battle_for_Azeroth"), ("Burning of Teldrassil — Warcraft Wiki", W+"Burning_of_Teldrassil"), ("N'Zoth — Warcraft Wiki", W+"N%27Zoth"), ("Zovaal — Warcraft Wiki", W+"Zovaal"), ("Shadowlands — Warcraft Wiki", W+"World_of_Warcraft:_Shadowlands")],
content="""
<p class="lede">The two most turbulent expansions in the game's history — the faction war's ugliest hour, the last Old God's bid for the world, and a detour into death itself that divided the playerbase and that Dragonflight deliberately walks away from. You need the events; you can skip the metaphysics.</p>

<h2>Battle for Azeroth: the war for the world's blood</h2>
<p>With <a class="cx" href="codex.html#azerite">Azerite</a> promising weapons beyond imagining, Warchief <a class="cx" href="codex.html#sylvanas">Sylvanas</a> strikes first: her armies burn the night elves' World Tree home of <a class="cx" href="codex.html#teldrassil">Teldrassil</a> with thousands of civilians inside — the setting's darkest single act by a faction leader, and one the story never lets the Horde launder. The Alliance answers by besieging her capital, the ruins of Lordaeron, which she blights and abandons. Both sides recruit island nations — the Alliance the seafaring kingdom of Kul Tiras, the Horde the ancient troll empire of Zandalar — and the war grinds through naval campaigns, assassinations, and atrocities, until the Horde's own conscience revolts. The old soldier <a class="cx" href="codex.html#saurfang">Varok Saurfang</a> challenges Sylvanas to ritual single combat before both armies; she kills him, but when he goads her into it she says the truth out loud — <em>"the Horde is nothing"</em> to her, all of them merely fuel — and her own faction abandons her on the spot. She flies away with her real plan intact. The factions, exhausted, sign an armistice.</p>
<p>Beneath the war runs the whisper. Queen <a class="cx" href="codex.html#azshara">Azshara</a> — ten thousand years a servant of <a class="cx" href="codex.html#nzoth">N'Zoth</a> — drags both navies to the sea floor and, through her own gloriously spiteful defeat in her Eternal Palace, achieves exactly what she wanted: the shattering of the last Old God's prison. N'Zoth — a drowned god, a vast squid-like bulk of eyes, maws, and cabled tendrils, each eye opening slowly as if amused — rises, seats his Black Empire's capital of Ny'alotha over Pandaria's scarred vale, and begins rewriting reality toward the Void's old dream of a corrupted world-soul. Armored in a titan-forged countermeasure, the heroes carry the fight into his waking nightmare-city, and the last of the four Old Gods is burned out of the universe. The Void Lords' ten-thousand-year plan on Azeroth dies with him — on the surface, at least.</p>

<h2>The sky torn open</h2>
<p>Then Sylvanas plays her hand. She rides to <a class="cx" href="codex.html#icecrown">Icecrown</a>, defeats the jailer Lich King <a class="cx" href="codex.html#bolvar">Bolvar</a>, and — rather than take the crown — <strong>shatters the <a class="cx" href="codex.html#helm">Helm of Domination</a></strong>, tearing open the sky above Northrend into the realm of Death itself. The armistice-weary world watches its heroes, Anduin among them, be dragged bodily into the <a class="cx" href="codex.html#shadowlands">Shadowlands</a>.</p>

<h2>Shadowlands: the machine of death</h2>
<p>The afterlife is revealed as a cosmic machinery of soul-triage — kyrian ferrymen, ancient forest rebirth-gods, honor-bound war-realms, vampiric sin-eaters — all of it starving, because every soul is being funneled instead into the torture-pit of the Maw. Its warden: <strong><a class="cx" href="codex.html#zovaal">Zovaal, the Jailer</a></strong> — a bald grey giant with molten eyes, wearing his prison-chains as ornaments, a glowing void in his chest where a sigil was torn out; a deposed and banished arbiter of Death who claims, with contested credibility, that nearly every catastrophe in this chronicle (the Helm, Frostmourne, the Lich King, and more) was a link in his design. His goal: reach the hidden workshop of reality's makers and rewrite existence into obedience. He dominates Anduin's body and will — the setting's kindest king made into its most tragic weapon — and for a time wields him as a new Arthas.</p>
<p>Sylvanas's whole story comes due here. Her bargain with the Jailer, struck in the despair after her death and centuries of torment, collapses when he finally states his endgame — not freedom from a rigged system of fate, but universal domination. She turns on him; the severed noble half of her soul is restored; and after his destruction at the raid's end, she is sentenced not to oblivion but to labor: to free, one by one, every soul her long war sent into the Maw. Anduin, freed but hollowed, walks away from his crown to wander. The heroes return home through the mended sky.</p>
<p>Out of universe: Shadowlands' cosmic scope-creep and retcons were badly received, and Blizzard said so almost openly in what came next. The story deliberately comes home — to soil, to dragons, to characters. That homecoming is the final chapter.</p>
"""),

dict(slug="14-eve-of-dragonflight", num="XIV", accent="#d9a84e",
era="The table is set", title="The Eve of Dragonflight",
sub="The Isles awaken, the dracthyr open their eyes, the Storm-Eater breaks her chains — and five mortal dragons fly home",
sources=[("Dragonflight — Warcraft Wiki", W+"World_of_Warcraft:_Dragonflight"), ("Dragon Isles — Warcraft Wiki", W+"Dragon_Isles"), ("Raszageth — Warcraft Wiki", W+"Raszageth"), ("Worldsoul Saga — Warcraft Wiki", W+"Worldsoul_Saga"), ("Midnight — Warcraft Wiki", W+"World_of_Warcraft:_Midnight")],
content="""
<p class="lede">For the first time in the game's history, no apocalypse is scheduled. The Legion is destroyed, the Old Gods are dead or silent, the Jailer is unmade, the faction war is signed away. Into that unprecedented quiet, a beacon older than any of it begins to burn.</p>

<h2>1 — The Isles awaken</h2>
<p>The <a class="cx" href="codex.html#dragon-isles">Dragon Isles</a> — dormant and hidden since the flights withdrew in Chapter III — flare back to life, and every dragon on Azeroth feels the call. <a class="cx" href="codex.html#alexstrasza">Alexstrasza</a> summons the flights home to rekindle their ancient oaths at the Isles' waygates and oathstones — and, perhaps, to seek what the Dragon Soul took from them: their Aspect-hood itself. Horde and Alliance, at peace for once, each send a grand expedition alongside them. That reawakening has a cause, not just a mood: with the titans' order-magic across the world disturbed and the world-soul's own blood spilled in Silithus, old seals everywhere are weakening. Including one in particular.</p>

<h2>2 — The dracthyr open their eyes</h2>
<p>On the Forbidden Reach, the <a class="cx" href="codex.html#dracthyr">dracthyr</a> — Neltharion's hidden soldiers, in stasis since the War of the Scaleborn — wake to a world twenty thousand years older than the one they fell asleep in. Their creator is millennia dead, and history remembers him as its greatest traitor. Two of their commanders, Emberthal and Azurathel, lead their weyrns out into a present that owes them nothing — one toward the Horde, one toward the Alliance. (This is the expansion's new playable race, the Evoker, and their identity crisis is the story's quietest, saddest thread: what do you do when your whole purpose was a dead tyrant's secret?)</p>

<h2>3 — The Storm-Eater breaks free</h2>
<p>Their waking is no accident. Elemental cultists — modern <a class="cx" href="codex.html#primalists">Primalists</a>, heirs of the old refusal — have already freed <a class="cx" href="codex.html#raszageth">Raszageth</a> from the Froststone Vault — a storm given wings, slate scales crawling with lightning, her laugh like splitting sky. The Storm-Eater's goals are exactly what they were twenty thousand years ago, with twenty thousand years of interest: shatter the ordered flights, free her three siblings from the <a class="cx" href="codex.html#vault-incarnates">Vault of the Incarnates</a>, and scour the titans' fingerprints from the world. And her old argument has never been harder to answer — the gods whose gift defined the Aspects are gone, the gift itself is spent, and <em>"why did you let them rewrite what we are?"</em> now lands on five mortals who privately wonder the same thing.</p>

<h2>4 — The wounds they carry home</h2>
<ul>
<li><strong>Alexstrasza</strong> returns as a queen without a crown's power, carrying every failure of her long watch — Neltharion's fall, Malygos's execution, the flights' dwindling eggs — and a specific, personal ache: it was her mercy that left the Incarnates alive to return.</li>
<li><strong><a class="cx" href="codex.html#nozdormu">Nozdormu</a></strong> knows, and has known for ages, a prophecy that he will one day fall and become <a class="cx" href="codex.html#murozond">Murozond</a>, the dragon of the end of time — and must guard the timeline anyway, a warden serving a sentence that ends in becoming the thing he guards against.</li>
<li><strong><a class="cx" href="codex.html#kalecgos">Kalecgos</a></strong> leads a blue flight reduced to a handful of scholars, heir to a madman's legacy and a nearly empty sky.</li>
<li><strong><a class="cx" href="codex.html#merithra">Merithra</a></strong> must grow into her dead mother Ysera's place as the green flight's leader — an Aspect-shaped hole she never asked to fill.</li>
<li><strong>The black flight</strong> has no Aspect at all — only rival heirs. <a class="cx" href="codex.html#wrathion">Wrathion</a> — in mortal guise a sharp-dressed young man with ember-red eyes and a schemer's smile — the purified-from-the-egg prince who once helped save the world and once catastrophically misjudged it; and <a class="cx" href="codex.html#sabellian">Sabellian</a>, Deathwing's scarred, imperious elder son, returned after decades guarding his brood on Outland. Between them stands <a class="cx" href="codex.html#ebyssian">Ebyssian</a> — who has spent millennia disguised as a black-furred, moose-antlered tauren spiritwalker — an uncorrupted black dragon wanting the job least of anyone, which, in this story, is a qualification. Underneath the succession fight is the deeper excavation the expansion promises: how, exactly, the Earth-Warder fell, and what he left buried.</li>
</ul>

<h2>5 — What kind of story this is</h2>
<p>Dragonflight is a deliberate change of key: no scheduled doomsday, no cosmic jailer — a warmer, slower expansion about renewal, inheritance, and what a guardian is for when the gods who commissioned her are gone. It is also, structurally, Blizzard's turn toward continuous, character-forward storytelling, a direction that carries into everything after.</p>

<details class="spoiler"><summary>Spoilers: where Dragonflight's own story goes (open only if you want the road ahead)</summary>
<p>The expansion's three raid-arcs: Raszageth succeeds in freeing her siblings at the cost of her own life (Vault of the Incarnates); Neltharion's buried laboratory Aberrus is opened, revealing the depth of his experiments and handing dangerous inheritance to the black flight's heirs while Iridikron seeks a darker prize (Aberrus, the Shadowed Crucible); and Fyrakk, empowered by shadowflame, assaults the Emerald Dream to burn the newly-growing World Tree Amirdrassil — dying at its heart, while Vyranoth, moved at last by Alexstrasza's stubborn friendship, breaks with the Incarnates (Amirdrassil, the Dream's Hope). Along the way Tyr is restored, the aspects are re-blessed — by Azeroth herself, not the titans, which quietly answers the Incarnates' old accusation — and Iridikron departs, essence of Galakrond in hand, to serve a new master: the harbinger Xal'atath, setting up the Worldsoul Saga.</p>
<p>That saga is the game's current era: <em>The War Within</em> (2024) took the fight beneath the world toward the world-soul herself; <em>Midnight</em> (March 2026) brings the Void's armies to the Sunwell and Quel'Thalas; and <em>The Last Titan</em> will close the trilogy in Northrend. In other words: the questions raised in Chapters I and II of this site — who gets to shape the sleeping god, and what the titans really intended — are finally, openly, the main plot.</p>
</details>

<div class="aside"><span class="aside-tag">You're ready</span> That's the whole table, set. Queue the cinematic, and watch five mortal dragons fly home.</div>
"""),
]
