# Chapters I-VII
W = "https://warcraft.wiki.gg/wiki/"

CHAPTERS_A = [
dict(slug="01-the-six-forces", num="I", accent="#9a7bdc",
era="Before the world", title="The Six Forces",
sub="The cosmology Warcraft never explains on screen — and why every villain makes sense once you know it",
sources=[("Cosmology — Warcraft Wiki", W+"Cosmology"), ("Titans — Warcraft Wiki", W+"Titan"), ("Void lords — Warcraft Wiki", W+"Void_lord"), ("Sargeras — Warcraft Wiki", W+"Sargeras"), ("World of Warcraft: Chronicle Volume 1 (Blizzard, 2016) — the canonical print source for this era", W+"World_of_Warcraft:_Chronicle_Volume_1")],
content="""
<p class="lede">The Warcraft universe is a tug-of-war between six primal forces, arranged in opposing pairs: <strong>Order and Disorder</strong>, <strong>Light and Void</strong>, <strong>Life and Death</strong>. Each force has its native realm, its energies, and its cosmic faction. The games almost never lay this out directly — it comes mostly from a companion book series called <em>World of Warcraft: Chronicle</em> — but almost every villain you will meet makes sense once you can place them on this map.</p>

<h2>Order — the <a class="cx" href="codex.html#titans">titans</a></h2>
<p>Titans are god-like beings of living metal and stone whose souls gestate inside planets. A planet with a titan soul growing within it is called a <a class="cx" href="codex.html#world-soul">world-soul</a>. This is the single most important fact in all of Warcraft: <strong><a class="cx" href="codex.html#azeroth">Azeroth</a>, the planet the game is played on, is a world-soul</strong> — and by every account the most powerful one ever found. Nearly every major villain in the franchise is, one way or another, fighting over this sleeping unborn god.</p>
<p>The awakened titans formed a council of six called the <strong>Pantheon</strong>, led by the Highfather <a class="cx" href="codex.html#amanthul">Aman'Thul</a>. They roamed the cosmos searching for slumbering kin, imposing order on chaotic worlds as they went. Because their sheer size and power could crush a fragile world-soul by accident, they rarely acted directly; instead they forged armies of servants from stone and metal — the <a class="cx" href="codex.html#titanforged">titan-forged</a> — and elevated the greatest of these into <strong>keepers</strong> to act in their stead.</p>

<h2>Disorder — <a class="cx" href="codex.html#sargeras">Sargeras</a> and the <a class="cx" href="codex.html#burning-legion">Burning Legion</a></h2>
<p>Sargeras was the Pantheon's champion — its foremost warrior, tasked with hunting demons across creation. In the course of that duty he interrogated captured servants of the Void and learned of their plan (below): to corrupt a world-soul and birth a god of their own. He drew a conclusion that broke him. A Void-corrupted Dark Titan would be worse than no universe at all — therefore every world that might host one must burn first.</p>
<p>When the Pantheon recoiled from this logic, Sargeras shattered them, scattered their spirits, and raised the demons he had spent eons imprisoning into an endless army: the Burning Legion. Among his most valuable recruits were two brilliant leaders of the <a class="cx" href="codex.html#eredar">eredar</a> people, <a class="cx" href="codex.html#kiljaeden">Kil'jaeden</a> the Deceiver and <a class="cx" href="codex.html#archimonde">Archimonde</a> the Defiler — names that will haunt every later chapter. For millennia the Legion scoured the cosmos of life, a guardian who had decided annihilation was mercy. Its ultimate target was always Azeroth.</p>

<h2>Void — the <a class="cx" href="codex.html#void-lords">Void Lords</a> and the <a class="cx" href="codex.html#old-gods">Old Gods</a></h2>
<p>Outside reality dwell the Void Lords: entities of pure hungering shadow who cannot easily enter the physical universe. Their plan is patient and horrifying: corrupt a world-soul <em>while it sleeps</em>, so that when it wakes, it wakes as theirs — an infinitely powerful Dark Titan of the Void. Their weapons are the Old Gods: mountain-sized parasites of tentacle and maw, hurled blindly across the cosmos at promising worlds like biological warheads. Four of them struck Azeroth. Their tools are whispers, madness, and time — corruption measured in ten-thousand-year increments.</p>

<h2>Light, Life, and Death</h2>
<p>The remaining three forces matter later, so file them away now. The <strong>Light</strong> is the source of the Holy magic wielded by priests and paladins; its purest children are the benevolent wind-chime beings called the <a class="cx" href="codex.html#naaru">naaru</a>. <strong>Life</strong> flows through nature, the <a class="cx" href="codex.html#wild-gods">Wild Gods</a>, and the <a class="cx" href="codex.html#emerald-dream">Emerald Dream</a>. And <strong>Death</strong> has an entire bureaucratic afterlife-machine of its own, the <a class="cx" href="codex.html#shadowlands">Shadowlands</a> — which the story mostly ignores until it becomes the entire plot of one very controversial expansion.</p>

<div class="aside"><span class="aside-tag">New to Warcraft?</span> Don't memorize the chart. Just hold onto three things: the planet is a sleeping god; the Void wants to corrupt her; and the fallen titan Sargeras decided it was better to burn her than lose her. Everything else in this site is the fallout.</div>
"""),

dict(slug="02-shaping-of-azeroth", num="II", accent="#45b39c",
era="The primordial age", title="The Shaping of Azeroth",
sub="The Black Empire, the war of stone against shadow, and the wound that became the Well of Eternity",
sources=[("Black Empire — Warcraft Wiki", W+"Black_Empire"), ("Old Gods — Warcraft Wiki", W+"Old_Gods"), ("Well of Eternity — Warcraft Wiki", W+"Well_of_Eternity"), ("Curse of flesh — Warcraft Wiki", W+"Curse_of_flesh")],
content="""
<p class="lede">Before the titans found her, Azeroth was a roiling world of primordial elements — and then the Old Gods fell from the sky.</p>

<h2>The Elemental Lords and the Black Empire</h2>
<p>Newborn Azeroth was ruled by warring spirits of fire, water, air, and earth, commanded by four <a class="cx" href="codex.html#elemental-lords">Elemental Lords</a>. When the four <a class="cx" href="codex.html#old-gods">Old Gods</a> — <a class="cx" href="codex.html#yshaarj">Y'Shaarj</a>, <a class="cx" href="codex.html#nzoth">N'Zoth</a>, <a class="cx" href="codex.html#cthun">C'Thun</a>, and <a class="cx" href="codex.html#yoggsaron">Yogg-Saron</a> — crashed into the world, they enslaved the elements, raised servant races of insect and faceless horror, and built a continent-spanning nightmare civilization: the <strong>Black Empire</strong>. Beneath it all, their roots bored down toward the sleeping world-soul, and the whisper-work of corruption began.</p>

<h2>The titan-forged war</h2>
<p>The Pantheon found Azeroth, understood what was growing inside her, and understood equally that they dared not fight on her surface themselves — beings their size could kill the world-soul by accident. So they forged armies. Legions of <a class="cx" href="codex.html#titanforged">titan-forged</a> warriors of stone and iron, led by the keepers — among them <a class="cx" href="codex.html#tyr">Tyr</a> the warrior, <a class="cx" href="codex.html#odyn">Odyn</a> the proud, and their peers — made war on the Black Empire for ages, shattering the Elemental Lords and banishing them into elemental prison-realms.</p>

<h2>The death of Y'Shaarj — and the wound it left</h2>
<p>Y'Shaarj, mightiest and most vile of the Old Gods, threatened to overwhelm even the keepers. So Aman'Thul broke the Pantheon's own rule: he reached down from the sky himself and <strong>tore Y'Shaarj bodily out of the planet's crust</strong>, ripping it apart. It was a victory and a catastrophe at once. The Old God's roots had grown so deep that tearing it free gouged a colossal wound in the world, and the arcane lifeblood of the world-soul herself came fountaining up through it. The keepers labored for ages to stabilize and ward the wound, and the becalmed lake of raw power it left behind was given a name that will echo through every chapter that follows: <strong>the <a class="cx" href="codex.html#well-of-eternity">Well of Eternity</a></strong>.</p>
<p>The lesson was learned in blood: the remaining three Old Gods were buried too deep to remove without killing the patient. So the titan-forged <strong>imprisoned N'Zoth, C'Thun, and Yogg-Saron underground</strong> in warded vaults, and hoped the wards would hold forever. Hold onto this above all: <em>the Old Gods are never gone, only buried.</em> Half the tragedies in this chronicle grow out of those prisons.</p>
<p>Even dead, Y'Shaarj kept killing. Its dying breath and scattered remains seeped into the land that would one day be called <a class="cx" href="codex.html#pandaria">Pandaria</a>, becoming a lingering evil called the <a class="cx" href="codex.html#sha">Sha</a> — negative emotion given monstrous form. Its preserved heart was sealed in a vault. Both come back to haunt Chapter XI.</p>

<h2>Ordering the world</h2>
<p>With the Empire broken, the keepers shaped and seeded the world: they raised mountains, calmed seas, empowered the great beast-spirits called <a class="cx" href="codex.html#wild-gods">Wild Gods</a>, and built machine-cities like <a class="cx" href="codex.html#ulduar">Ulduar</a> to watch over the Old Gods' prisons. They also built new servant races of stone and metal to maintain it all — and here the Old Gods got their revenge. From their prisons they seeded a disease into the titan-forged called the <a class="cx" href="codex.html#curse-of-flesh">curse of flesh</a>, softening metal and stone into skin and bone over generations. The keepers' stone servants degenerated — as the Old Gods intended, to make them mortal and corruptible — into beings of flesh: the ancestors of <a class="cx" href="codex.html#mortal-races">humans, dwarves, and gnomes</a>. The joke of the setting is that most of its "ordinary" mortal races are broken machines, and the tragedy is that the curse worked exactly as designed.</p>
"""),

dict(slug="03-age-of-dragons", num="III", accent="#d4634f",
era="The age of dragons", title="The Age of Dragons",
sub="Galakrond, the five Aspects, the dracthyr, and the war against those who refused the titans' gift",
sources=[("Dragon Aspects — Warcraft Wiki", W+"Dragon_Aspects"), ("Primal Incarnates — Warcraft Wiki", W+"Primal_Incarnates"), ("Vault of the Incarnates — Warcraft Wiki", W+"Vault_of_the_Incarnates"), ("Dracthyr — Warcraft Wiki", W+"Dracthyr"), ("The Story So Far: the Dragon Aspects — Blizzard", "https://news.blizzard.com/en-us/article/23876527/the-story-so-far-take-wing-through-time-with-the-dragon-aspects")],
content="""
<p class="lede">This chapter is the direct foundation of the Dragonflight expansion. Everything it is about — the Aspects, the Dragon Isles, the enemies waiting in the vault — begins here.</p>

<h2>Galakrond, the not-quite-father of dragons</h2>
<p>Among Azeroth's native creatures were the <strong>proto-dragons</strong>: clever, feral, elemental beasts. One of them, <a class="cx" href="codex.html#galakrond">Galakrond</a>, grew monstrous — devouring his own kind, swelling into a mountain of hunger whose victims rose again as undead horrors. Keeper Tyr saw the threat when his fellow keepers would not, and found his answer in five unusually brilliant proto-dragons who had learned to survive Galakrond together: <strong>Alexstrasza, Malygos, Neltharion, Nozdormu, and Ysera</strong>. Under Tyr's guidance they warred against Galakrond and — at terrible cost, including Tyr's own hand, later replaced with one of silver — brought the leviathan down.</p>

<h2>The making of the Aspects</h2>
<p>Tyr proposed that these five heroes be empowered as Azeroth's permanent guardians. Keeper Odyn objected furiously — to him dragons were primitive animals, and only titan-forged could be trusted with the world — but the other keepers overruled him, and Odyn stormed off to found his own hall of warriors instead. The Pantheon itself answered Tyr's call: each titan channeled a portion of their power through the keepers into one proto-dragon, transforming the five into the <strong><a class="cx" href="codex.html#aspect">Dragon Aspects</a></strong>, each charged with a domain of the world's protection:</p>
<ul>
<li><strong><a class="cx" href="codex.html#alexstrasza">Alexstrasza the Life-Binder</a></strong> — a mountain range of ruby scale and molten-gold horn: queen of the red flight and of all dragonkind, guardian of all living things.</li>
<li><strong><a class="cx" href="codex.html#ysera">Ysera the Dreamer</a></strong> — emerald-scaled, her eyes closed even waking, seeing the <a class="cx" href="codex.html#emerald-dream">Emerald Dream</a> — nature's verdant blueprint-realm — more clearly than the waking world. Alexstrasza's sister.</li>
<li><strong><a class="cx" href="codex.html#nozdormu">Nozdormu the Timeless One</a></strong> — bronze as coin-metal, trailing streams of sand in flight: warden of time and the one true timeline.</li>
<li><strong><a class="cx" href="codex.html#malygos">Malygos the Spell-Weaver</a></strong> — a dragon of ice-blue crystal, raw magic visibly coursing beneath translucent scales: steward of arcane magic.</li>
<li><strong><a class="cx" href="codex.html#neltharion">Neltharion the Earth-Warder</a></strong> — basalt-black and broad as a hill, steadiest and best-loved of the five: guardian of the earth and the deep places.</li>
</ul>
<p>Other proto-dragons embraced the titans' gift and became the five ordered <a class="cx" href="codex.html#dragonflights">dragonflights</a>. Their homeland and seat of power was the <strong><a class="cx" href="codex.html#dragon-isles">Dragon Isles</a></strong> — the setting, twenty thousand years later, of the Dragonflight expansion.</p>

<h2>The dracthyr — Neltharion's secret soldiers</h2>
<p>Not all of Neltharion's work was noble even then. Seeking a perfect soldier, he created the <a class="cx" href="codex.html#dracthyr">dracthyr</a>: slender humanoid dragonkin — scaled, winged, mailed in their own hide, able to fold themselves into unassuming mortal "visage" forms — blending the essence of all five flights, organized into military weyrns and bound to his command through an artifact called the Oathbinder. They are the playable race Dragonflight introduces — and the reason they're new to everyone, dragons included, is coming two paragraphs from now.</p>

<h2>The Incarnates and the War of the Scaleborn</h2>
<p>Not every proto-dragon accepted the titans' gift. Some saw the Aspects as slaves — their very bodies rewritten in a foreign god's image — and rallied around four champions of raw elemental power, the <strong><a class="cx" href="codex.html#primalists">Primal Incarnates</a></strong>: <a class="cx" href="codex.html#raszageth">Raszageth</a> the Storm-Eater, slate scales crawling with lightning; <a class="cx" href="codex.html#iridikron">Iridikron</a> the Stonescaled, basalt-plated and patient as a geological era; <a class="cx" href="codex.html#vyranoth">Vyranoth</a> the Frozenheart, glacier-white and courteous and cold; and <a class="cx" href="codex.html#fyrakk">Fyrakk</a> the Blazing, wreathed in his own fire and given to shrieking glee. Their followers, the Primalists, drank deep of elemental power. Their grievance was not cartoonish: <em>why did you let alien gods rewrite what we are?</em> Vyranoth, once Alexstrasza's dear friend, joined last and most reluctantly — a friendship-turned-cold that Dragonflight mines for real pathos.</p>
<p>The result was the <strong>War of the Scaleborn</strong>, roughly twenty thousand years before the game's present. It opened with disaster: Raszageth struck the dracthyr's home, shattered the Oathbinder, and in desperation Neltharion did something that should chill you in hindsight — <strong>he listened, for the first time, to whispers rising from the deep places he guarded</strong>, and used their power to banish Raszageth into the Froststone Vault. Shaken, he sealed his now-uncontrollable dracthyr legions in stasis and hid them away, where they would sleep for twenty millennia.</p>
<p>The war ground on for years. In the end the Aspects won, but Alexstrasza could not bring herself to execute former kin: the remaining three Incarnates were sealed alive in the <strong><a class="cx" href="codex.html#vault-incarnates">Vault of the Incarnates</a></strong> — Nozdormu locked the inner gate with time, Malygos warded the outer door with arcane, and Neltharion buried the whole vault in the earth. Mercy, it turns out, is a loan the future has to repay.</p>
<p>Ages later, when the titans' magic waned from the Isles, the flights withdrew to the wider world, and their homeland slept — waiting.</p>
"""),

dict(slug="04-sundering", num="IV", accent="#4f9fe0",
era="Ten thousand years ago", title="Azshara and the Sundering",
sub="The golden empire of the night elves, the first Legion invasion, and the breaking of the world",
sources=[("War of the Ancients — Warcraft Wiki", W+"War_of_the_Ancients"), ("Great Sundering — Warcraft Wiki", W+"Great_Sundering"), ("Queen Azshara — Warcraft Wiki", W+"Queen_Azshara"), ("Demon Soul — Warcraft Wiki", W+"Demon_Soul"), ("Illidan Stormrage — Warcraft Wiki", W+"Illidan_Stormrage")],
content="""
<p class="lede">The Well of Eternity — the warded wound from Chapter II — sat at the heart of the world's single ancient continent. The elves who settled its shores drank of its power and became the <a class="cx" href="codex.html#night-elves">night elves</a>, the kaldorei: violet-skinned and towering, with luminous silver or amber eyes, at home under moonlight in old-growth forest. Their civilization became the mightiest the mortal world has ever known. Then it burned in a single generation.</p>

<h2>The Light of Lights</h2>
<p>Queen <a class="cx" href="codex.html#azshara">Azshara</a> — golden-eyed, silver-tressed, called the most beautiful being ever born; brilliant, vain, magnificent, genuinely adored — ruled the kaldorei at their golden height, surrounded by her arcane elite, the Highborne. Their ever-more-reckless drawing on the Well blazed like a beacon into the dark between the stars, and Sargeras saw it. Whispering through the Well, he seduced the queen and her court with promises of a perfected world. They opened a portal in the Well's depths, and for the first time the <a class="cx" href="codex.html#burning-legion">Burning Legion</a> poured into Azeroth.</p>

<h2>The War of the Ancients</h2>
<p>The war that followed drew in everyone. Three young night elves stepped into legend: the druid <a class="cx" href="codex.html#malfurion">Malfurion Stormrage</a>, stag-antlered and green-bearded, the first mortal to learn Cenarius's arts; the priestess <a class="cx" href="codex.html#tyrande">Tyrande Whisperwind</a>, white-haired and silver-eyed, armored in moonlight; and Malfurion's twin brother <a class="cx" href="codex.html#illidan">Illidan</a> — amber-eyed where his people's are silver, gifted, envious, and hungry for power; a love triangle and a moral fault-line in one family. Beside them fought the demigod <a class="cx" href="codex.html#cenarius">Cenarius</a>, the Wild Gods, and all five dragonflights.</p>
<p>Then came the betrayal this whole site keeps circling. <a class="cx" href="codex.html#neltharion">Neltharion</a>, ten thousand years into the Old Gods' whispers, proposed a weapon to end the war: a golden disc into which each flight poured a portion of its essence. He named it the Dragon Soul. When he unleashed it, he turned it on demon and dragon alike — nearly annihilating the blue flight in a single stroke — declared himself <strong>Deathwing the Destroyer</strong>, and shattered the unity of dragonkind forever. The disc, later renamed the <a class="cx" href="codex.html#demon-soul">Demon Soul</a>, holds the power of all five flights <em>except</em> his own; remember it, because it returns twice in later chapters, once to wound him and once to kill him.</p>
<p>Illidan, meanwhile, played his own double game with the Legion, and in the war's aftermath committed a sin his people could not forgive — recreating a new Well of Eternity from stolen vials of the old one's waters. His brother imprisoned him beneath the mountains for ten thousand years. File that away for Chapter VIII.</p>

<h2>The Sundering</h2>
<p>The defenders' final gambit was to destroy the Well itself and sever the Legion's anchor to the world. It worked — catastrophically. The Well's implosion tore the single continent apart into the seas and scattered landmasses of the modern map: <a class="cx" href="codex.html#kalimdor">Kalimdor</a> in the west, the <a class="cx" href="codex.html#eastern-kingdoms">Eastern Kingdoms</a> in the east, frozen <a class="cx" href="codex.html#northrend">Northrend</a> at the top of the world. This is <strong>the Great <a class="cx" href="codex.html#sundering">Sundering</a></strong>, the calendar-zero of Warcraft history. Azshara and her drowning court were caught at the bottom of the new sea — not by death, but by <a class="cx" href="codex.html#nzoth">N'Zoth</a>, who remade them into the <a class="cx" href="codex.html#naga">naga</a> — sea-serpents with torsos and arms, finned and scaled, their queen grown titanic and many-armed. Azshara traded one dark patron for another, and settled in to scheme for ten thousand years.</p>

<h2>Nordrassil and the long vigil</h2>
<p>On the new world's tallest peak, Mount Hyjal, the surviving night elves planted a colossal World Tree, <a class="cx" href="codex.html#nordrassil">Nordrassil</a>, over the scarred remnant of the Well. Alexstrasza, Ysera, and Nozdormu together blessed it — and through Ysera's blessing the night elves were granted immortality so long as the tree stood. The kaldorei turned their backs on arcane magic, embraced Cenarius's druidism, and kept a quiet vigil over the world's wounds. The age of empires gave way to long, slow millennia — which is exactly where the next chapter picks up.</p>

<div class="aside"><span class="aside-tag">New to Warcraft?</span> If you remember one thing: the Sundering is the "before" and "after" line of this whole setting. Every date you'll ever see in Warcraft lore is measured against either this event or the opening of the Dark Portal in Chapter VI.</div>
"""),

dict(slug="05-quiet-millennia", num="V", accent="#aab3c9",
era="The ten thousand quiet years", title="The Quiet Millennia",
sub="The elves splinter, the mortal kingdoms rise, and one bloodline is cursed to guard the world",
sources=[("Sunwell — Warcraft Wiki", W+"Sunwell"), ("Guardian of Tirisfal — Warcraft Wiki", W+"Guardian_of_Tirisfal"), ("Medivh — Warcraft Wiki", W+"Medivh"), ("Arathor — Warcraft Wiki", W+"Arathor"), ("Troll Wars — Warcraft Wiki", W+"Troll_Wars")],
content="""
<p class="lede">Ten thousand years pass between the Sundering and the first Warcraft game. They are quiet only by comparison. This chapter sets every playing piece on the board.</p>

<h2>The elven diaspora</h2>
<p>Not all night elves accepted the new ascetic order. Exiled for refusing to abandon arcane magic, a faction of Highborne sailed east to the Eastern Kingdoms and founded the kingdom of <a class="cx" href="codex.html#quelthalas">Quel'Thalas</a> — a realm of eternal autumn, gold-leafed forests threaded with white-and-gold spires. There they became the <a class="cx" href="codex.html#blood-elves">high elves</a> — smaller, sun-loving, day-walking — and, using a stolen vial of the old Well's waters, kindled a new fount of power at their kingdom's heart: the <strong><a class="cx" href="codex.html#sunwell">Sunwell</a></strong>. Its radiance fed every high elf's soul. That dependency is a loaded gun on the wall; it fires in Chapter VIII.</p>

<h2>Trolls, humans, and the first human empire</h2>
<p>The elves had built their kingdom on land the ancient <a class="cx" href="codex.html#trolls">troll</a> empires considered theirs, and the trolls — the Eastern Kingdoms' oldest power, ancestors from whom the night elves themselves had long ago evolved — made war to reclaim it. Desperate, the high elves turned to a rising young people: <a class="cx" href="codex.html#mortal-races">humanity</a>, descendants of the curse-of-flesh titan-forged, now united under the empire of <strong>Arathor</strong>. In exchange for aid, the elves taught a hundred humans magic. Together they broke the troll empires — and human civilization never looked back. Arathor eventually fractured into the <strong>Seven Kingdoms</strong> you'll hear named for the rest of the story: proud <a class="cx" href="codex.html#lordaeron">Lordaeron</a> in the north, mage-ruled <a class="cx" href="codex.html#dalaran">Dalaran</a>, seafaring Kul Tiras, mountain Alterac, knightly Stromgarde, forested Gilneas, and far to the south, <a class="cx" href="codex.html#stormwind">Stormwind</a>.</p>
<p>The dwarves delved their mountain city of Ironforge, the gnomes built beside them, and out west on Kalimdor the nomadic <a class="cx" href="codex.html#tauren">tauren</a> followed the herds while the night elves kept their forests. The <a class="cx" href="codex.html#pandaren">pandaren</a>, walled off behind impenetrable mists since before the Sundering, kept their own hidden peace with the Sha. The board is nearly set.</p>

<h2>The Guardian of Tirisfal</h2>
<p>Human mages learned quickly that demons still slipped into the world through the cracks. In secret, elven and human magi founded a council that would pour the power of many into a single champion: the <strong><a class="cx" href="codex.html#guardian">Guardian of Tirisfal</a></strong>, one mortal empowered far beyond mortal limits to fight the Legion's infiltrators in the shadows. For generations the title passed down — until it reached <a class="cx" href="codex.html#aegwynn">Aegwynn</a>, a Guardian so mighty she struck down an avatar of Sargeras himself. Or so she believed. In truth, the fallen titan's spirit slipped from the broken avatar into the one place she never looked: her own unborn son. And here is the detail that makes the next two chapters possible — Aegwynn had long since stopped trusting the council that empowered her, so she hid the whole affair from them: the battle, the victory, and the child. Nobody was watching the next Guardian, because nobody knew there was one.</p>
<p>That son was <strong><a class="cx" href="codex.html#medivh">Medivh</a></strong> — the last Guardian, the most powerful mortal alive, and, from before his birth, the sleeper vessel of Sargeras. He grew up alongside two friends in Stormwind: the future king Llane Wrynn, and the future war-hero <a class="cx" href="codex.html#lothar">Anduin Lothar</a> — last living descendant of the old Arathi royal line — the bloodline that once united every human kingdom, and the reason seven of them will one day agree to follow him. The stage is set. All that's missing is an army — and Sargeras, wearing Medivh's face, knew exactly where to find one.</p>
"""),

dict(slug="06-fall-of-draenor", num="VI", accent="#cf8342",
era="Another world entirely", title="The Fall of Draenor",
sub="The orcs, the draenei, a demon's bargain, and the opening of the Dark Portal",
sources=[("Draenor — Warcraft Wiki", W+"Draenor"), ("Draenei — Warcraft Wiki", W+"Draenei"), ("Orc — Warcraft Wiki", W+"Orc"), ("Gul'dan — Warcraft Wiki", W+"Gul%27dan"), ("Dark Portal — Warcraft Wiki", W+"Dark_Portal")],
content="""
<p class="lede">Leave Azeroth for a moment. On a savage, beautiful world called <a class="cx" href="codex.html#outland">Draenor</a>, two peoples are about to be destroyed by the same lie.</p>

<h2>Two peoples</h2>
<p>The <a class="cx" href="codex.html#orcs">orcs</a> of Draenor lived in shamanistic clans — massive, tusked, <em>brown-skinned</em> hunters and mystics bound to the elements, honorable by their own hard code. (Yes, brown: the green comes later, and it is not natural.) Their neighbors were refugees: the <a class="cx" href="codex.html#draenei">draenei</a>, "exiled ones" — tall, blue-to-lavender skinned, with cranial crests, tendrils, tails, and hooves, their cities grown from glowing crystal — a fragment of the eredar race who had fled their homeworld of <a class="cx" href="codex.html#argus">Argus</a> twenty-five thousand years earlier, when Sargeras came recruiting. Their leader, the prophet <a class="cx" href="codex.html#velen">Velen</a> — ancient, white-bearded, his milky eyes seeing the future more clearly than the room — had refused the bargain his two closest friends accepted — Kil'jaeden and Archimonde, who became the Legion's greatest lieutenants. Guided by the Light-beings called <a class="cx" href="codex.html#naaru">naaru</a>, Velen's people had run from world to world for millennia. On Draenor, at last, they thought they were safe.</p>
<p>Kil'jaeden never stopped hunting them. And when the Legion found Draenor, it chose not to invade but to <em>arrange</em> things — because a corrupted people makes a better weapon than a conquered one.</p>

<h2>The blood of Mannoroth</h2>
<p>Working through the orcs' own spiritual leaders — first the elder shaman <a class="cx" href="codex.html#nerzhul">Ner'zhul</a>, who balked when he glimpsed the truth, then his ruthless apprentice <a class="cx" href="codex.html#guldan">Gul'dan</a> — a hunched, hooded figure bent over a skull-topped staff, fel-green light leaking from his eyes — who did not — Kil'jaeden fed the clans a story that the draenei were plotting their destruction. Shamanism withered; Gul'dan's new warlock magic spread, and the fel energies seeping through the clans began turning brown skin sickly green even in those who never touched it. Then, at a gathering of the clans, the chieftains drank the blood of the demon lord <a class="cx" href="codex.html#mannoroth">Mannoroth</a> — a pit lord, a tusked dinosaur bulk fused to a giant's torso — binding themselves body and soul to the Legion's bloodlust. The transformation finished overnight: green skin, furnace-red eyes, and a hunger that had to go somewhere. Of the great chieftains, only <a class="cx" href="codex.html#durotan">Durotan</a> of the Frostwolves refused the cup. His clan was exiled to the frozen north for it, and Durotan himself was murdered on the road for saying out loud what Gul'dan had done — but not before his infant son survived the ambush and was found, in a basket beside his dead parents, by a human lord. Hold that thought; it pays off in two chapters.</p>
<p>What followed was genocide. The united Horde — a name coined by Gul'dan's puppet warchief — fell upon the draenei and slaughtered them almost to extinction, Velen and a remnant fleeing into hiding. But a weapon, once used, needs a new target, and the demon-blood fury did not fade. The orcs began to turn on each other. Gul'dan needed a new war — and his true master, speaking through a sleeping Guardian on a world called Azeroth, offered him one.</p>

<h2>The Dark Portal</h2>
<p>Sargeras-in-<a class="cx" href="codex.html#medivh">Medivh</a> reached across the void to Gul'dan and struck the bargain that starts the Warcraft franchise proper: power for the warlock, an army for the titan. On one side stood the mightiest mortal mage of Azeroth; on the other, the warlocks of a corrupted world. Together they tore open a wound between the two planets — <strong>the <a class="cx" href="codex.html#dark-portal">Dark Portal</a></strong> — and the starving, blood-cursed Horde marched through it into the quiet southern forests of Stormwind.</p>

<div class="aside"><span class="aside-tag">New to Warcraft?</span> This is the setting's second great "before and after" line. Warcraft dates everything from either the Sundering or this moment — the opening of the Dark Portal, year zero of the modern era.</div>
"""),

dict(slug="07-first-second-wars", num="VII", accent="#b04a4a",
era="Year 0 – 8 after the Portal", title="The First and Second Wars",
sub="Stormwind falls, the Alliance rises, Draenor dies — and a captive soul is forged into the Lich King",
sources=[("First War — Warcraft Wiki", W+"First_War"), ("Second War — Warcraft Wiki", W+"Second_War"), ("Alliance of Lordaeron — Warcraft Wiki", W+"Alliance_of_Lordaeron"), ("Medivh — Warcraft Wiki", W+"Medivh"), ("Anduin Lothar — Warcraft Wiki", W+"Anduin_Lothar"), ("Garona Halforcen — Warcraft Wiki", W+"Garona_Halforcen"), ("Orgrim Doomhammer — Warcraft Wiki", W+"Orgrim_Doomhammer"), ("Ner'zhul — Warcraft Wiki", W+"Ner%27zhul"), ("Lich King — Warcraft Wiki", W+"Lich_King")],
content="""
<p class="lede">These are the events of the original two strategy games, compressed to what still matters. By this chapter's end, every doom of the next twenty years will already be in motion.</p>

<h2>The First War — the fall of Stormwind</h2>
<p>The Horde came up out of the southern swamps, and the kingdom of <a class="cx" href="codex.html#stormwind">Stormwind</a> went to meet it, and lost. That much is an ordinary war story. What is not ordinary is <em>why</em>.</p>
<p>On paper Stormwind should have held. It was a serious kingdom with a serious army, and the orcs — savage, certainly, but riven by clan feuds and fighting on ground they had never seen — were not the better force. The humans kept losing anyway, and for years nobody could work out how. Intelligence went astray. Defenses failed in ways that made no sense. Every plan the crown made seemed to reach the enemy before it reached the front. The answer was that the kingdom's single greatest asset was also its leak: <a class="cx" href="codex.html#medivh">Medivh</a>, the last Guardian of Tirisfal, the most powerful mortal alive — and, since before his birth, the chair Sargeras had been sitting in.</p>
<p>Two men worked it out. <a class="cx" href="codex.html#lothar">Anduin Lothar</a>, the finest soldier of his generation and Medivh's oldest friend, and <a class="cx" href="codex.html#khadgar">Khadgar</a>, a young apprentice the Guardian had taken in — who had been quietly noticing things he was not meant to notice. They climbed the tower at <a class="cx" href="codex.html#karazhan">Karazhan</a> and killed him. It was not a clean fight or a triumphant one: at the very end Medivh surfaced — the real one, the friend, appalled at what had been done with his hands — and the dying magic aged Khadgar into an old man's body where he stood. He was in his twenties. He never got the years back. Sargeras's spirit was driven out into the shadows, which is not the same as destroyed. Merely inconvenienced.</p>
<p>It came too late for the kingdom. A half-orc interpreter named <a class="cx" href="codex.html#garona">Garona</a> — planted in the court, and compelled by a spell she could not refuse — reached King Llane in his own throne room, and the capital fell within the year. Lothar put what was left of his people on ships: soldiers, refugees, and the murdered king's seven-year-old son, a boy named <a class="cx" href="codex.html#varian">Varian</a>, watching his father's city burn from the deck. They sailed north across the sea to <a class="cx" href="codex.html#lordaeron">Lordaeron</a>, where Lothar arrived at another king's court as a beggar with a warning — a hard thing for a proud man to be.</p>

<h2>The Second War — the Alliance of Lordaeron</h2>
<p>Confronted with the refugees' testimony, King <a class="cx" href="codex.html#terenas">Terenas Menethil II</a> of Lordaeron managed what none of his ancestors ever had: he got the human kingdoms to agree. The Seven Kingdoms, the dwarves and gnomes, and — reluctantly, honoring a debt four thousand years old from the troll wars of Chapter V — the high elves of <a class="cx" href="codex.html#quelthalas">Quel'Thalas</a> came under one banner, the <strong><a class="cx" href="codex.html#alliance">Alliance</a> of Lordaeron</strong>. The elves did the minimum, and left early, and left angry. File that away: it is the opening move of a very slow divorce.</p>
<p>Against them stood a Horde at its terrible height under Warchief <a class="cx" href="codex.html#orgrim">Orgrim Doomhammer</a> — worth understanding, because he is not a monster. He was a competent commander of a corrupted army: a Blackrock orc who had spent years watching warlocks run his people through a puppet warchief, and who finally killed the puppet, took the ancestral hammer, and tried to fight a real war with what the warlocks had left him. Twice it looked as though he would win it.</p>
<p>It turned on treachery. At the decisive hour, with the outcome genuinely in doubt, <a class="cx" href="codex.html#guldan">Gul'dan</a> took a third of the army off the field to chase a sunken tomb he believed held a god's power. It held his death instead — his own demons tore him apart in the dark — and the missing third cost the Horde the war. Lothar died at the foot of Blackrock mountain, still fighting, and never saw the alliance he had built hold together; his lieutenant <a class="cx" href="codex.html#turalyon">Turalyon</a> picked up the broken banner and finished the campaign, breaking the Horde at the gates of its last redoubt. The <a class="cx" href="codex.html#dark-portal">Dark Portal</a> was thrown down.</p>
<p>The surviving orcs were penned in internment camps, and there something happened that nobody had planned for. Cut off from demonic power for the first time in a generation, they went grey. They sat down. They stopped wanting anything at all. It was withdrawal — but their jailers saw docility, wrote the orc problem down as solved, and stopped watching the camps. Among the prisoners was a boy raised from infancy by a human lord as a slave and a gladiator, and given a slave's name for what he was: <a class="cx" href="codex.html#thrall">Thrall</a>, son of the murdered Frostwolf chieftain <a class="cx" href="codex.html#durotan">Durotan</a>. Remember him; he's the future.</p>

<h2>The death of Draenor</h2>
<p>Back on the orcs' dying homeworld, <a class="cx" href="codex.html#nerzhul">Ner'zhul</a> — the old shaman Gul'dan had betrayed and supplanted — made one final grab for greatness, tearing open portals to new worlds for the remnant Horde to flee through. The overlapping portal energies ripped Draenor apart. An Alliance expedition (Khadgar and Turalyon among them) was stranded on the far side as the world shattered into the floating wreckage later called <strong><a class="cx" href="codex.html#outland">Outland</a></strong>.</p>

<h2>The forging of the Lich King</h2>
<p>Ner'zhul escaped the explosion — into Kil'jaeden's waiting hands. There is a grim symmetry worth naming here: every version of this man is a victim of the one before it. Deceived by Kil'jaeden, supplanted by his own apprentice, and now collected by the demon he first said no to. None of which stops any of it from being his fault. The Legion had one more use for the old shaman. His body was destroyed and his spirit bound into a suit of armor and a runeblade, sealed inside a block of ice, and hurled down onto the frozen roof of Azeroth, <a class="cx" href="codex.html#northrend">Northrend</a>. His purpose: to spread a plague of undeath and raise an army — the <a class="cx" href="codex.html#scourge">Scourge</a> — to soften Azeroth for the Legion's next invasion. His new name was the <strong><a class="cx" href="codex.html#lich-king">Lich King</a></strong>, and his prison-throne of ice held two artifacts you must remember: the <a class="cx" href="codex.html#helm">Helm of Domination</a> that housed his will, and a hungering sword, waiting to be found, named <a class="cx" href="codex.html#frostmourne">Frostmourne</a>.</p>
"""),
]
