# Visual layer for the codex: appearance descriptions (prepended to entries)
# and warcraft.wiki.gg article links (each wiki page leads with character/location art).
W = "https://warcraft.wiki.gg/wiki/"

# Prepended to the codex description. Keep to one vivid sentence.
APPEARANCE = {
# Characters & Beings
"adal": "A constellation of white-gold light folded into the shape of a great crystalline mobile, turning slowly in the air and chiming as it moves.",
"aegwynn": "A stern, ageless human woman in green traveling robes, wearing eight centuries as if they were forty years.",
"akama": "A stooped, grey-skinned draenei with a face of drooping tendrils and blind-looking eyes, moving like a man who has carried one secret too long.",
"alexstrasza": "In dragon form a mountain range of ruby scale and molten-gold horn; in her preferred elf-like guise, a tall flame-haired woman with sweeping horns, gold-scaled raiment, and eyes like banked embers.",
"algalon": "A humanoid figure made of night sky — armored in dark bronze, his body an aperture onto wheeling constellations, a live star burning where a face should be.",
"amanthul": "A titan vast beyond sight — a bearded colossus of bronze living metal whose hand alone could palm a mountain range.",
"anachronos": "In dragon form a great sand-gold serpent hazed with drifting motes of time; in mortal guise, a robed elf with hourglass eyes and no patience for small talk.",
"anduin": "A slight, golden-haired young man in white-and-gold, more priest than king, carrying his father's greatsword like a borrowed weight.",
"archimonde": "A tower of grey-blue muscle with burning green eyes, curling horns swept back like a crown, and arms that end in taloned hands large enough to crush siege towers.",
"arthas": "In life, a broad-shouldered golden prince in the silver-and-blue of Lordaeron; after Frostmourne, a white-haired revenant in black saronite plate, skin gone corpse-pale, eyes burning ice-blue.",
"arugal": "A gaunt old wizard in tattered violet robes, hair wild, hands never quite still, speaking to wolves as though they were his sons.",
"azshara": "In life, the most beautiful night elf ever born — golden-eyed, silver-tressed, draped in the sun-and-moon splendor of her empire; beneath the sea, a many-armed serpent empress grown titanic, crowned in coral and hubris.",
"bolvar": "A paladin burned beyond death: blackened, cracked skin over inner fire, so that he smolders inside his armor like a coal wearing a crown.",
"brann": "A weathered, red-bearded dwarf in travel-worn leathers, festooned with map cases and digging tools, grinning at a hole in the ground.",
"cenarius": "A demigod half night elf, half stag — antlered, moss-bearded, his lower body a great deer's, his skin bark and starlight.",
"chromie": "A small white-haired gnome in bronze-trimmed robes, radiating helpfulness; the dragon underneath is a slender sand-gold serpent she rarely bothers to be.",
"cthun": "A single lidless eye the size of a temple dome, wreathed in a fringe of tentacles, set in a body of pulsing chitin beneath the sand.",
"darion": "A death knight in blackened plate under a tattered hood, skin corpse-grey, eyes burning the pale blue of the Scourge that made him.",
"durotan": "A broad, brown-skinned orc in frostwolf furs, black-bearded, carrying himself with the stillness of a man who has already counted the cost.",
"ebyssian": "In mortal guise, a black-furred Highmountain tauren with great moose-like antlers; in truth, one of the last uncorrupted black dragons, obsidian-scaled and calm-eyed.",
"fandral": "A severe night elf archdruid crowned with a great rack of stag antlers, robes of leaf and bark, mouth set in a permanent line of disapproval.",
"fyrakk": "A proto-dragon of fire — ember-scaled, wreathed in flame, wings like sheets of burning canvas, given to shrieking glee.",
"galakrond": "A proto-dragon swollen to the size of a flying mountain — pallid, five-limbed, reeking of carrion, his throat sacs bulging with the not-quite-dead.",
"garrosh": "A mahogany-skinned Mag'har orc built like a siege engine, jaw tattooed black, shoulders spiked with the tusks of his kills, swinging his father's axe Gorehowl.",
"grommash": "A wiry, ferocious orc with a black-tattooed jaw and — after the demon's cup — eyes gone furnace-red; his axe Gorehowl screams through the air holes bored in its blade.",
"guardian": "Not a person but an office: one mortal at a time, invested with the pooled might of a secret council — recognizable less by look than by the impossible weight of power they carry.",
"guldan": "A hunched, hooded orc warlock bent nearly double over a skull-topped staff, fel-green light leaking from his eyes and from the runes carved into his skin.",
"illidan": "A night elf with burned-out eye sockets bound in cloth, fel tattoos coiling over his skin — and, after his bargain in Outland, horns, hooves, and vast leathery wings: half elf, half demon, wholly his own side.",
"iridikron": "A proto-dragon of living stone — slate-grey, basalt-plated, slow-speaking and patient as a geological era, the strategist of the four.",
"jaina": "A blonde human archmage in violet and white; in later years her hair turns winter-white with a single gold streak — the cost of everything she has watched burn.",
"kaelthas": "A golden-haired elf prince of impossible poise, robed in red and gold, three glowing green orbs orbiting his shoulders like captive suns.",
"kalecgos": "A sapphire-scaled dragon; in mortal guise, a blue-haired half-elf scholar with kind, tired eyes — bookish where his predecessor was imperious.",
"kelthuzad": "A lich: a floating, frost-bound skeleton in tattered arcane finery, spine trailing into chains and ice where legs should be, voice like a purring cat in a crypt.",
"khadgar": "A young man in an old man's body — white-bearded, barrel-chested, bright-eyed, endlessly amused, usually accompanied by a raven.",
"kiljaeden": "A crimson-skinned eredar grown to demigod scale, with vast folded wings, cloven hooves, and a smile engineered across twenty-five thousand years of salesmanship.",
"liadrin": "A red-armored blood elf woman with a severe blonde bob and green fel-touched eyes, bearing a Light-forged blade she once had to steal the right to carry.",
"lich-king": "A throne of black ice, a jagged crown, and a voice underneath the world: whoever wears the Helm appears as a towering armored revenant with frost-fire eyes.",
"loken": "A towering titan-forged figure of dark metal and stormlight, handsome in the way a statue is, crackling with the lightning of the forge that made him.",
"lothar": "A greying lion of a man in Stormwind blue — heavy mustache, heavier greatsword, the last of an ancient knightly bloodline.",
"magtheridon": "A colossal red-black demon on hooked, crab-like legs, wings in rags, chained spread-eagled above his own blood-tanks.",
"maiev": "A night elf in segmented silver-green armor and a full helm that shows only glowing eyes, carrying a crescent moonblade on a chain.",
"malfurion": "A green-bearded night elf crowned with stag antlers, arms feathering into talons when he wills it — the first mortal druid, smelling of rain and loam.",
"malganis": "A dreadlord in deep blue-black hide, ram-horned and bat-winged, with the unhurried courtesy of something that has already won.",
"malygos": "A dragon of ice-blue crystal and silver, arcane power visibly coursing under translucent scale plates like light through deep water.",
"mannoroth": "A pit lord: a four-legged demon bulk like a tusked dinosaur fused to a giant's torso, wings ragged, every breath a furnace.",
"medivh": "A raven-haired, hawk-faced mage in feathered robes who is often, in fact, the raven you just saw — keeper of the lonely tower of Karazhan.",
"merithra": "An emerald dragon with her mother's grace and none of her serenity; in elf guise, a green-haired woman whose eyes stay open — and worried.",
"moira": "A dwarf princess in Dark Iron black and red, dark-haired and pale as ash, wearing her adopted clan's colors like an argument.",
"murozond": "Nozdormu unmade: the same bronze frame gone void-black and rotted with wrongness, sand spilling from his joints like a broken hourglass.",
"muru": "A naaru dimmed nearly to darkness — a slow-turning crystalline form gone void-black at the edges, chiming faintly, like a wind chime running out of wind.",
"nefarian": "An enormous black dragon gone gaunt and skeletal at the joints, his hide scored with surgical scars; in mortal guise, a sallow, courteous human lord.",
"neltharion": "Once a basalt-black mountain of a dragon, steady as the deep earth; as Deathwing, a horror of cracked obsidian plates riveted with glowing elementium over a body literally too full of magma to hold itself together, jaw sheathed in metal.",
"nerzhul": "A stooped, white-braided elder orc shaman hung with wolf fetishes — and later, no body at all: a spirit fused to armor and ice.",
"nozdormu": "A dragon of bronze and streaming sand, scales like coin-metal in sunlight; in mortal guise, a bronzed elf lord with hourglass-gold eyes and infinite, weary patience.",
"nzoth": "A drowned god: a vast squid-like bulk of eyes, maws, and cabled tendrils, each eye opening slowly, as if amused.",
"odyn": "A titan-forged giant of golden metal and white beard, one eye traded for sight into the shadow — a boisterous, iron-certain war-king in a gilded hall.",
"onyxia": "A black dragon of polished obsidian with a fan of horns and an unnervingly amused set to her jaw; as Prestor, a raven-haired noblewoman everyone finds it easier to agree with.",
"orgrim": "A heavy-shouldered orc in black plate scored with clan runes, jaw set, the great black Doomhammer resting across one shoulder.",
"ragnaros": "A giant of living magma rising waist-deep out of a lava lake, molten rock cracking across his shoulders, wielding a hammer of white-hot iron.",
"raszageth": "A proto-dragon of storm — slate scales crawling with lightning, feather-edged wings that crack thunder, a laugh like splitting sky.",
"rexxar": "A huge tusked half-breed in a skull-faced helm and furs, twin axes at his back, flanked by a bear and a hawk that obey him better than most soldiers.",
"sabellian": "An obsidian-scaled black dragon of the old broods; in mortal form, a scarred, imperious man in dark plate who has spent centuries expecting betrayal.",
"sargeras": "A titan in blackened bronze armor, beard and eyes replaced by fel fire, wielding a sword the length of a continent — the largest single figure in the setting's cosmos.",
"saurfang": "A massive grey-haired orc in scarred plate, tusks yellowed with age, carrying an axe he plainly wishes he could put down.",
"sylvanas": "In life, a golden-haired high elf ranger-general in forest leathers; in undeath, ashen-skinned and red-eyed beneath a dark hood, her bow a recurve of black horn — beautiful the way a knife is.",
"thaurissan": "A Dark Iron dwarf king with ash-grey skin and a fire-lit beard, robed in black and molten orange on a throne cut from cooled lava.",
"thrall": "A green-skinned orc with rare blue eyes, broad as a door, by turns in black plate armor and simple shaman's wolf-furs, the warhammer Doomhammer across his back.",
"tirion": "An old, white-bearded paladin in silver-and-gold plate, weathered as a fencepost, holding a sword that burns with contained daylight.",
"turalyon": "A fair-haired paladin knight of Lordaeron; after a thousand years of war beyond the stars, gone silver, scarred, and faintly luminous with the Light.",
"tyr": "A titan-forged keeper of silver-grey metal, one hand lost to Galakrond and replaced with a fist of pure silver — the model, some say, for every human ideal of the noble knight.",
"tyrande": "A white-haired night elf priestess with luminous silver eyes, armored in moonlight and starmetal, a crescent glaive in hand and a saber-toothed nightsaber at her side.",
"uther": "A greying bull of a paladin in gold-chased plate and holy-book chains, warhammer in hand — the standard every knight of the Light is measured against.",
"vancleef": "A lean human in a red bandana mask and a long coat, hands scarred by honest work, standing on the deck of a warship built inside a mine.",
"varian": "A scarred, heavy-browed human king with a wolf's temper, twin swords crossed at his back over Stormwind blue-and-gold.",
"varimathras": "A tall, ash-grey dreadlord with folded bat wings and swept-back horns, all courtly manners and visible calculation.",
"vashj": "A naga sea-witch: six arms, a mane of living serpents, and a serpent's body armored in shell and spite.",
"velen": "An ancient draenei — lavender skin gone pale, long white beard, forehead crest like a crown of bone, milky eyes that see the future more clearly than the room.",
"voljin": "A lanky, hunched jungle troll with cobalt skin, a red mohawk, long tusks, and a shadow hunter's rush of masks and glaives.",
"vyranoth": "A proto-dragon of frost — glacier-white, rimed in permanent hoarfrost, still and courteous and cold as the deep winter.",
"wrathion": "In mortal guise, a sharp-dressed young man with umber skin, ember-red eyes, and a small black chin-beard — every inch the charming schemer; in truth, a sleek obsidian dragon barely grown.",
"xavius": "The first satyr: a night elf lord warped into a goat-legged, horned demon of shadow and smirk, trailing nightmare like smoke.",
"yoggsaron": "A god that is mostly mouths: a heaving mass of green-black flesh, ropes of ichor, and grins in the dark, self-described as the lucid dream the wounds of the world whisper through.",
"ysera": "An emerald dragon whose eyes remain closed even waking, seeing the Dream instead; in elf guise, a green-haired woman with antlers and rainbow-sheened wings, speaking as if half in sleep.",
"yshaarj": "The worst of them: a mountain of black flesh with seven grinning heads, so vast its removal left a wound that became a sea.",
"zovaal": "A bald grey giant with molten eyes, bound in rune-chains he has long since made into ornaments, a glowing void where a sigil was torn from his chest.",
# Peoples & Factions
"alliance": "Banners of blue and gold; white stone, gryphons, cathedral bells.",
"argent-crusade": "Silver-and-gold tabards over practical plate, camped in disciplined rows on the ice beneath the Lich King's fortress.",
"blood-elves": "Slender, golden-haired elves with luminous green eyes (the fel tint of their addiction's darkest years), robed in crimson and gold beneath eternal-autumn trees.",
"broken": "Hunched, grey-skinned draenei with drooping facial tendrils and broken horns, their crystal cities long since traded for caves.",
"burning-legion": "A sky gone green: meteors of fel fire, infernal war machines, and demon legions in blackened bronze without end.",
"cenarion-circle": "Druids in leaf-green and antlered headdresses, camped wherever the land is worst injured.",
"cult-of-the-damned": "Hooded figures in bone-white and sickly green, working grain mills and crypts with equal enthusiasm.",
"dark-iron": "Dwarves with ash-grey skin and eyes like banked coals, beards shot through with ember-light, dressed in blackened iron.",
"defias": "Bandits in red bandana masks working the roads and farms of Westfall, organized far better than bandits have any business being.",
"dracthyr": "Slender humanoid dragons — scaled, winged, mailed in their own hide — who can fold themselves into unassuming elf-like 'visage' forms.",
"draenei": "Tall, blue-to-lavender skinned exiles with cranial crests, tendrils, tails, and hooves, their cities grown from glowing pink-white crystal.",
"dragonflights": "Five colors on the wind: ruby, emerald, bronze, sapphire, and obsidian, each flight bearing its Aspect's charge.",
"ebon-blade": "Death knights in black saronite plate with ice-blue eyes, riding skeletal horses that leave frost in the grass.",
"elemental-lords": "Four living cataclysms: a firelord of magma and rage, a wind-prince of storm, a stone tyrant, and a tide-queen.",
"eredar": "The template the word 'demon' now brings to mind — horned, hooved, tailed magi of terrible elegance, in crimson and grey-blue.",
"forsaken": "The free-willed dead: grey flesh, glowing amber eyes, bone showing at the joints, banners of tattered violet.",
"horde": "Banners of red and black; spiked iron, wolf totems, drums.",
"infinite-dragonflight": "Dragons of oily black and violet shot through with fractured, running clockwork light — bronzes turned photographic negative.",
"kirin-tor": "Archmages in violet and gold beneath a floating city's spires, each robe worth a small kingdom.",
"mortal-races": "Stocky mountain-folk, small ingenious tinkerers, and adaptable plains-and-castle humans — flesh where their ancestors were stone and steel.",
"naaru": "Beings of pure Light: floating, chiming constellations of golden crystal shards, wordless and warm.",
"naga": "Sea-serpents with torsos and arms — finned, scaled, trident-armed — the drowned court remade for the deep.",
"nathrezim": "Tall demons of ash-grey and blue hide with ram's horns and folded bat wings, dressed like diplomats and behaving like them.",
"night-elves": "Violet-skinned, silver- or amber-eyed elves of towering height, at home in moonlit old-growth forest; their cities grow rather than stand.",
"old-gods": "Mountains of eyes, maws, and tentacle wreathed in whisper — flesh that should not be, at planetary scale.",
"orcs": "Massive tusked warriors — born brown-skinned; the fel blood of their corruption turned the race green.",
"pandaren": "Black-and-white bear-folk of unhurried good humor, brewers and monks in a landscape of jade and mist.",
"primalists": "Elemental zealots in storm-, flame-, frost-, and stone-wrought armor, and the proto-dragons who lead them.",
"scarlet-crusade": "Crusaders in white tabards blazoned with a red cross, immaculate, burning as much as they cleanse.",
"scourge": "A tide of the walking dead — skeletal soldiers, patchwork abominations, frost wyrms of bare bone — under a plague-green sky.",
"shadow-council": "Robed warlocks working by green fel-light in cellars and caves, faces hidden, summoning circles already drawn.",
"tauren": "Towering bison-folk with great horns and gentle voices, dwelling in painted hide tents on golden plains.",
"titanforged": "Warriors of animate stone and metal — some like giants of granite, the keepers like demigods of bronze and silver.",
"titans": "Beings the size of moons: living metal and stone, star-fields for eyes, worlds for cradles.",
"trolls": "Tall, wiry, tusked, and long-eared, in totemic empires of stone ziggurats — blue-skinned in the jungles, forest-green in the woods, sand-hued in the deserts.",
"twilights-hammer": "Cultists in twilight purple and bruise-blue, masked and hooded, tattooed with things that hurt to look at directly.",
"void-lords": "Never truly seen: presences of hungering shadow at the edge of reality, known only by their weapons and their whispers.",
"wild-gods": "Beast-spirits at demigod scale — a moon-white tiger, a great bear, a raven that is also a storm — wreathed in the Dream's green light.",
"worgen": "Hunched wolf-men with matted fur and yellow eyes, wearing the ruined finery of the Gilnean gentry they used to be.",
# Places & Realms
"ahnqiraj": "Colossal sandstone gates half-swallowed by dunes, opening on a hive of chitin-ribbed halls that were grown rather than built.",
"argus": "A scarred sphere of fel-green fire and shattered crust, hanging in Azeroth's sky like an accusing eye during the Legion's last war.",
"azeroth": "Seen from above: a blue-green world of two great continents flanking a storm-wracked central sea — and, at its molten heart, a sleeping god.",
"black-temple": "A fortress-temple of green-black stone in Outland's ash wastes, its draenei grace buried under demon iron.",
"blackrock": "A black cone venting smoke over a cracked, ash-choked valley, its interior a vertical city of forges and lava falls.",
"dalaran": "A walled city of violet spires and gold domes floating inside its own weather, the underside a raw disc of torn bedrock.",
"dark-portal": "A colossal free-standing gateway of green-lit black stone, flanked by hooded statues, its interior a sheet of boiling emerald void.",
"dragon-isles": "A hidden subcontinent of primeval valleys, titan spires, and waterfalls the height of mountains, lit as if the world were still new.",
"dragonblight": "A grey frozen plain studded with dragon skeletons the size of cathedrals, snow drifting through their ribs.",
"eastern-kingdoms": "A north-south chain of kingdoms: golden elf-forests at the crown, plagued heartlands, dwarven snow-peaks, and Stormwind's green south.",
"emerald-dream": "Azeroth as it would be without mortals: the same world, endless-green, dreaming — its sky aurora'd, its forests vast beyond age.",
"icecrown": "A black saronite spire rising from a glacier, ringed by walls of ice and the frozen dead — visible for miles, warm nowhere.",
"kalimdor": "The wilder western continent: moonlit elf forests in the north, golden savannas and red desert canyons in the south.",
"karazhan": "A lone black tower on a dead hill under a permanently overcast sky, its windows lit by parties that ended centuries ago.",
"lordaeron": "Once white-stone towns and autumn fields under cathedral bells; now the Plaguelands — sick ochre earth, blighted air, and the ruined capital's silent throne.",
"naxxramas": "A vast floating ziggurat of bone-coloured stone and green necrotic light, hanging over the countryside like a verdict.",
"nordrassil": "A World Tree crowning Mount Hyjal's snow-peak, its canopy in the clouds, the scarred well glimmering among its roots.",
"northrend": "The frozen crown of the world: glacier coasts, howling tundra, and the green-lit vaults of dead empires beneath.",
"orgrimmar": "A fortress-city of red desert rock, dark iron, and spiked palisades, banners snapping in canyon wind.",
"outland": "The shattered corpse of Draenor: floating islands over an endless nether-sky, red wastes, fungal marsh, and one impossible green valley.",
"pandaria": "Jade forests, terraced emerald valleys, and cloud-wrapped peaks — a continent like a landscape painting, with something dark sealed under the floorboards.",
"quelthalas": "A kingdom of eternal autumn: gold-leafed forests threaded with white-and-gold spires, warm long after sunset.",
"shadowlands": "The afterlife as cosmos: a shattered sky of realms — gold-winged Bastion, autumnal Ardenweald, gothic Revendreth — all orbiting the screaming pit of the Maw.",
"shattrath": "Terraced rings of pale stone rising to a lit central spire, packed with refugees of every people the Legion has ever displaced.",
"silithus": "A wind-scoured southern desert of hives and ruins — now dominated by a continent-sized sword standing hilt-to-heaven in a wound of gold.",
"stormwind": "A proud human city of white stone and blue slate roofs, canals and cathedral square, rebuilt stone by stone after its fall.",
"stratholme": "A burned grid of stone streets under permanent orange overcast, the fires never quite out, the dead never quite still.",
"sunwell": "A fount of liquid gold light in a white-and-gold sanctum at Quel'Thalas's northern isle — less a place than a heartbeat.",
"teldrassil": "A World Tree grown into an island: an entire night elf civilization in its boughs, purple-canopied, moon-silvered — before the fire.",
"ulduar": "A titan city of bronze, stone, and snow in Northrend's peaks — half temple, half machine, its vaults humming over a prison.",
"undercity": "Green-lit vaulted sewers and apothecary halls under a shattered royal city, the air thick enough to taste.",
"vault-incarnates": "A titan-built prison sunk in a storm-wracked crag of the Isles: rings of ordered stone and arcane seals around four cells of elemental fury.",
"well-of-eternity": "An inland sea of silver-gold starlight at the heart of the old world, its surface currents moving like slow galaxies.",
# Artifacts & Substances
"ashbringer": "A great two-handed sword whose blade burns white-gold along its length; corrupted, the same steel runs black and bleeds red light.",
"azerite": "Veins and boulders of glowing amber-gold crystal — warm, faintly pulsing, unmistakably alive.",
"demon-soul": "A featureless disc of perfect gold, small enough to palm, heavy with the essence of four dragonflights.",
"doomhammer": "A heavy black maul with a squared head and a haft wrapped in worn leather, plain to the point of severity.",
"frostmourne": "A long pale runeblade, fuller etched with burning blue runes, a horned skull at the guard — cold that hungers.",
"heart-yshaarj": "A house-sized black heart, still beating after ten thousand years, veined in sha-white.",
"helm": "A jagged crown-helm of dark saronite, ice-blue light burning through its eye slits even when no one wears it.",
"sword-sargeras": "A blade of blackened metal the height of a mountain range, driven to the hilt into the desert of Silithus, wound-light glowing at its base.",
}

# warcraft.wiki.gg article for each entry (the page's infobox art is the visual reference).
WIKI = {
"adal": W+"A%27dal", "aegwynn": W+"Aegwynn", "ahnqiraj": W+"Ahn%27Qiraj",
"akama": W+"Akama", "alexstrasza": W+"Alexstrasza", "algalon": W+"Algalon_the_Observer",
"alliance": W+"Alliance", "amanthul": W+"Aman%27Thul", "anachronos": W+"Anachronos",
"anduin": W+"Anduin_Wrynn", "archimonde": W+"Archimonde", "argent-crusade": W+"Argent_Crusade",
"argus": W+"Argus", "arthas": W+"Arthas_Menethil", "arugal": W+"Arugal",
"ashbringer": W+"Ashbringer", "aspect": W+"Dragon_Aspects", "azerite": W+"Azerite",
"azeroth": W+"Azeroth", "azshara": W+"Queen_Azshara", "black-temple": W+"Black_Temple",
"blackrock": W+"Blackrock_Mountain", "blood-elves": W+"Blood_elf", "bolvar": W+"Bolvar_Fordragon",
"brann": W+"Brann_Bronzebeard", "broken": W+"Broken", "burning-legion": W+"Burning_Legion",
"cenarion-circle": W+"Cenarion_Circle", "cenarius": W+"Cenarius", "chromie": W+"Chronormu",
"cthun": W+"C%27Thun", "cult-of-the-damned": W+"Cult_of_the_Damned", "curse-of-flesh": W+"Curse_of_flesh",
"dalaran": W+"Dalaran", "darion": W+"Darion_Mograine", "dark-iron": W+"Dark_Iron_dwarf",
"dark-portal": W+"Dark_Portal", "defias": W+"Defias_Brotherhood", "demon-soul": W+"Demon_Soul",
"doomhammer": W+"Doomhammer", "dracthyr": W+"Dracthyr", "draenei": W+"Draenei",
"dragon-isles": W+"Dragon_Isles", "dragonblight": W+"Dragonblight", "dragonflights": W+"Dragonflight_(dragon)",
"durotan": W+"Durotan", "eastern-kingdoms": W+"Eastern_Kingdoms", "ebon-blade": W+"Knights_of_the_Ebon_Blade",
"ebyssian": W+"Ebyssian", "elemental-lords": W+"Elemental_Lord", "emerald-dream": W+"Emerald_Dream",
"eredar": W+"Eredar", "fandral": W+"Fandral_Staghelm", "forsaken": W+"Forsaken",
"frostmourne": W+"Frostmourne", "fyrakk": W+"Fyrakk", "galakrond": W+"Galakrond",
"garrosh": W+"Garrosh_Hellscream", "grommash": W+"Grommash_Hellscream", "guardian": W+"Guardian_of_Tirisfal",
"guldan": W+"Gul%27dan", "heart-yshaarj": W+"Heart_of_Y%27Shaarj", "helm": W+"Helm_of_Domination",
"horde": W+"Horde", "icecrown": W+"Icecrown_Citadel", "illidan": W+"Illidan_Stormrage",
"infinite-dragonflight": W+"Infinite_dragonflight", "iridikron": W+"Iridikron", "jaina": W+"Jaina_Proudmoore",
"kaelthas": W+"Kael%27thas_Sunstrider", "kalecgos": W+"Kalecgos", "kalimdor": W+"Kalimdor",
"karazhan": W+"Karazhan", "kelthuzad": W+"Kel%27Thuzad", "khadgar": W+"Khadgar",
"kiljaeden": W+"Kil%27jaeden", "kirin-tor": W+"Kirin_Tor", "liadrin": W+"Lady_Liadrin",
"lich-king": W+"Lich_King", "loa": W+"Loa", "loken": W+"Loken",
"lordaeron": W+"Lordaeron", "lothar": W+"Anduin_Lothar", "magtheridon": W+"Magtheridon",
"maiev": W+"Maiev_Shadowsong", "malfurion": W+"Malfurion_Stormrage", "malganis": W+"Mal%27Ganis",
"malygos": W+"Malygos", "mannoroth": W+"Mannoroth", "medivh": W+"Medivh",
"merithra": W+"Merithra", "moira": W+"Moira_Thaurissan", "mortal-races": W+"Curse_of_flesh",
"murozond": W+"Murozond", "muru": W+"M%27uru", "naaru": W+"Naaru",
"naga": W+"Naga", "nathrezim": W+"Nathrezim", "naxxramas": W+"Naxxramas",
"nefarian": W+"Nefarian", "neltharion": W+"Deathwing", "nerzhul": W+"Ner%27zhul",
"night-elves": W+"Night_elf", "nordrassil": W+"Nordrassil", "northrend": W+"Northrend",
"nozdormu": W+"Nozdormu", "nzoth": W+"N%27Zoth", "odyn": W+"Odyn",
"old-gods": W+"Old_Gods", "onyxia": W+"Onyxia", "orcs": W+"Orc",
"orgrim": W+"Orgrim_Doomhammer", "orgrimmar": W+"Orgrimmar", "outland": W+"Outland",
"pandaren": W+"Pandaren", "pandaria": W+"Pandaria", "primalists": W+"Primalists",
"quelthalas": W+"Quel%27Thalas", "ragnaros": W+"Ragnaros", "raszageth": W+"Raszageth",
"rexxar": W+"Rexxar", "sabellian": W+"Sabellian", "sargeras": W+"Sargeras",
"saurfang": W+"Varok_Saurfang", "scarlet-crusade": W+"Scarlet_Crusade", "scourge": W+"Scourge",
"sha": W+"Sha", "shadow-council": W+"Shadow_Council", "shadowlands": W+"Shadowlands",
"shattrath": W+"Shattrath_City", "silithus": W+"Silithus", "stormwind": W+"Stormwind_City",
"stratholme": W+"Stratholme", "sundering": W+"Great_Sundering", "sunwell": W+"Sunwell",
"sword-sargeras": W+"Sword_of_Sargeras", "sylvanas": W+"Sylvanas_Windrunner", "tauren": W+"Tauren",
"teldrassil": W+"Teldrassil", "thaurissan": W+"Dagran_Thaurissan", "thrall": W+"Thrall",
"tirion": W+"Tirion_Fordring", "titanforged": W+"Titan-forged", "titans": W+"Titan",
"trolls": W+"Troll", "turalyon": W+"Turalyon", "twilights-hammer": W+"Twilight%27s_Hammer",
"tyr": W+"Tyr", "tyrande": W+"Tyrande_Whisperwind", "ulduar": W+"Ulduar",
"undercity": W+"Undercity", "uther": W+"Uther_the_Lightbringer", "vancleef": W+"Edwin_VanCleef",
"varian": W+"Varian_Wrynn", "varimathras": W+"Varimathras", "vashj": W+"Lady_Vashj",
"vault-incarnates": W+"Vault_of_the_Incarnates", "velen": W+"Velen", "void-lords": W+"Void_lord",
"voljin": W+"Vol%27jin", "vyranoth": W+"Vyranoth", "well-of-eternity": W+"Well_of_Eternity",
"wild-gods": W+"Wild_God", "worgen": W+"Worgen", "world-soul": W+"World-soul",
"wrathgate": W+"Battle_of_Angrathar_the_Wrathgate", "wrathion": W+"Wrathion", "xavius": W+"Xavius",
"yoggsaron": W+"Yogg-Saron", "ysera": W+"Ysera", "yshaarj": W+"Y%27Shaarj",
"zovaal": W+"Zovaal",
}
