# Visual layer for the codex: appearance descriptions (prepended to entries)
# and warcraft.wiki.gg article links (each wiki page leads with character/location art).
W = "https://warcraft.wiki.gg/wiki/"

# Prepended to the codex description. Keep to one vivid sentence.
APPEARANCE = {
# Characters & Beings
"aegwynn": "A stern, ageless human woman in green traveling robes, wearing eight centuries as if they were forty years.",
"alexstrasza": "In dragon form a mountain range of ruby scale and molten-gold horn; in her preferred elf-like guise, a tall flame-haired woman with sweeping horns, gold-scaled raiment, and eyes like banked embers.",
"amanthul": "A titan vast beyond sight — a bearded colossus of bronze living metal whose hand alone could palm a mountain range.",
"anduin": "A slight, golden-haired young man in white-and-gold, more priest than king, carrying his father's greatsword like a borrowed weight.",
"archimonde": "A tower of grey-blue muscle with burning green eyes, curling horns swept back like a crown, and arms that end in taloned hands large enough to crush siege towers.",
"arthas": "In life, a broad-shouldered golden prince in the silver-and-blue of Lordaeron; after Frostmourne, a white-haired revenant in black saronite plate, skin gone corpse-pale, eyes burning ice-blue.",
"azshara": "In life, the most beautiful night elf ever born — golden-eyed, silver-tressed, draped in the sun-and-moon splendor of her empire; beneath the sea, a many-armed serpent empress grown titanic, crowned in coral and hubris.",
"bolvar": "A paladin burned beyond death: blackened, cracked skin over inner fire, so that he smolders inside his armor like a coal wearing a crown.",
"cenarius": "A demigod half night elf, half stag — antlered, moss-bearded, his lower body a great deer's, his skin bark and starlight.",
"cthun": "A single lidless eye the size of a temple dome, wreathed in a fringe of tentacles, set in a body of pulsing chitin beneath the sand.",
"ebyssian": "In mortal guise, a black-furred Highmountain tauren with great moose-like antlers; in truth, one of the last uncorrupted black dragons, obsidian-scaled and calm-eyed.",
"fyrakk": "A proto-dragon of fire — ember-scaled, wreathed in flame, wings like sheets of burning canvas, given to shrieking glee.",
"galakrond": "A proto-dragon swollen to the size of a flying mountain — pallid, five-limbed, reeking of carrion, his throat sacs bulging with the not-quite-dead.",
"garrosh": "A mahogany-skinned Mag'har orc built like a siege engine, jaw tattooed black, shoulders spiked with the tusks of his kills, swinging his father's axe Gorehowl.",
"grommash": "A wiry, ferocious orc with a black-tattooed jaw and — after the demon's cup — eyes gone furnace-red; his axe Gorehowl screams through the air holes bored in its blade.",
"guldan": "A hunched, hooded orc warlock bent nearly double over a skull-topped staff, fel-green light leaking from his eyes and from the runes carved into his skin.",
"guardian": "Not a person but an office: one mortal at a time, invested with the pooled might of a secret council — recognizable less by look than by the impossible weight of power they carry.",
"illidan": "A night elf with burned-out eye sockets bound in cloth, fel tattoos coiling over his skin — and, after his bargain in Outland, horns, hooves, and vast leathery wings: half elf, half demon, wholly his own side.",
"iridikron": "A proto-dragon of living stone — slate-grey, basalt-plated, slow-speaking and patient as a geological era, the strategist of the four.",
"jaina": "A blonde human archmage in violet and white; in later years her hair turns winter-white with a single gold streak — the cost of everything she has watched burn.",
"kaelthas": "A golden-haired elf prince of impossible poise, robed in red and gold, three glowing green orbs orbiting his shoulders like captive suns.",
"kalecgos": "A sapphire-scaled dragon; in mortal guise, a blue-haired half-elf scholar with kind, tired eyes — bookish where his predecessor was imperious.",
"kelthuzad": "A lich: a floating, frost-bound skeleton in tattered arcane finery, spine trailing into chains and ice where legs should be, voice like a purring cat in a crypt.",
"khadgar": "A young man in an old man's body — white-bearded, barrel-chested, bright-eyed, endlessly amused, usually accompanied by a raven.",
"kiljaeden": "A crimson-skinned eredar grown to demigod scale, with vast folded wings, cloven hooves, and a smile engineered across twenty-five thousand years of salesmanship.",
"lich-king": "A throne of black ice, a jagged crown, and a voice underneath the world: whoever wears the Helm appears as a towering armored revenant with frost-fire eyes.",
"lothar": "A greying lion of a man in Stormwind blue — heavy mustache, heavier greatsword, the last of an ancient knightly bloodline.",
"malfurion": "A green-bearded night elf crowned with stag antlers, arms feathering into talons when he wills it — the first mortal druid, smelling of rain and loam.",
"malygos": "A dragon of ice-blue crystal and silver, arcane power visibly coursing under translucent scale plates like light through deep water.",
"mannoroth": "A pit lord: a four-legged demon bulk like a tusked dinosaur fused to a giant's torso, wings ragged, every breath a furnace.",
"medivh": "A raven-haired, hawk-faced mage in feathered robes who is often, in fact, the raven you just saw — keeper of the lonely tower of Karazhan.",
"merithra": "An emerald dragon with her mother's grace and none of her serenity; in elf guise, a green-haired woman whose eyes stay open — and worried.",
"murozond": "Nozdormu unmade: the same bronze frame gone void-black and rotted with wrongness, sand spilling from his joints like a broken hourglass.",
"neltharion": "Once a basalt-black mountain of a dragon, steady as the deep earth; as Deathwing, a horror of cracked obsidian plates riveted with glowing elementium over a body literally too full of magma to hold itself together, jaw sheathed in metal.",
"nerzhul": "A stooped, white-braided elder orc shaman hung with wolf fetishes — and later, no body at all: a spirit fused to armor and ice.",
"nozdormu": "A dragon of bronze and streaming sand, scales like coin-metal in sunlight; in mortal guise, a bronzed elf lord with hourglass-gold eyes and infinite, weary patience.",
"nzoth": "A drowned god: a vast squid-like bulk of eyes, maws, and cabled tendrils, each eye opening slowly, as if amused.",
"odyn": "A titan-forged giant of golden metal and white beard, one eye traded for sight into the shadow — a boisterous, iron-certain war-king in a gilded hall.",
"raszageth": "A proto-dragon of storm — slate scales crawling with lightning, feather-edged wings that crack thunder, a laugh like splitting sky.",
"sabellian": "An obsidian-scaled black dragon of the old broods; in mortal form, a scarred, imperious man in dark plate who has spent centuries expecting betrayal.",
"sargeras": "A titan in blackened bronze armor, beard and eyes replaced by fel fire, wielding a sword the length of a continent — the largest single figure in the setting's cosmos.",
"sylvanas": "In life, a golden-haired high elf ranger-general in forest leathers; in undeath, ashen-skinned and red-eyed beneath a dark hood, her bow a recurve of black horn — beautiful the way a knife is.",
"thrall": "A green-skinned orc with rare blue eyes, broad as a door, by turns in black plate armor and simple shaman's wolf-furs, the warhammer Doomhammer across his back.",
"turalyon": "A fair-haired paladin knight of Lordaeron; after a thousand years of war beyond the stars, gone silver, scarred, and faintly luminous with the Light.",
"tyr": "A titan-forged keeper of silver-grey metal, one hand lost to Galakrond and replaced with a fist of pure silver — the model, some say, for every human ideal of the noble knight.",
"tyrande": "A white-haired night elf priestess with luminous silver eyes, armored in moonlight and starmetal, a crescent glaive in hand and a saber-toothed nightsaber at her side.",
"uther": "A greying bull of a paladin in gold-chased plate and holy-book chains, warhammer in hand — the standard every knight of the Light is measured against.",
"varian": "A scarred, heavy-browed human king with a wolf's temper, twin swords crossed at his back over Stormwind blue-and-gold.",
"vashj": "A naga sea-witch: six arms, a mane of living serpents, and a serpent's body armored in shell and spite.",
"velen": "An ancient draenei — lavender skin gone pale, long white beard, forehead crest like a crown of bone, milky eyes that see the future more clearly than the room.",
"voljin": "A lanky, hunched jungle troll with cobalt skin, a red mohawk, long tusks, and a shadow hunter's rush of masks and glaives.",
"vyranoth": "A proto-dragon of frost — glacier-white, rimed in permanent hoarfrost, still and courteous and cold as the deep winter.",
"wrathion": "In mortal guise, a sharp-dressed young man with umber skin, ember-red eyes, and a small black chin-beard — every inch the charming schemer; in truth, a sleek obsidian dragon barely grown.",
"xavius": "The first satyr: a night elf lord warped into a goat-legged, horned demon of shadow and smirk, trailing nightmare like smoke.",
"yoggsaron": "A god that is mostly mouths: a heaving mass of green-black flesh, ropes of ichor, and grins in the dark, self-described as the lucid dream the wounds of the world whisper through.",
"ysera": "An emerald dragon whose eyes remain closed even waking, seeing the Dream instead; in elf guise, a green-haired woman with antlers and rainbow-sheened wings, speaking as if half in sleep.",
"yshaarj": "The worst of them: a mountain of black flesh with seven grinning heads, so vast its removal left a wound that became a sea.",
"zovaal": "A bald grey giant with molten eyes, bound in rune-chains he has long since made into ornaments, a glowing void where a sigil was torn from his chest.",

# Peoples & Factions
"alliance": "Banners of blue and gold; white stone, gryphons, cathedral bells.",
"blood-elves": "Slender, golden-haired elves with luminous green eyes (the fel tint of their addiction's darkest years), robed in crimson and gold beneath eternal-autumn trees.",
"burning-legion": "A sky gone green: meteors of fel fire, infernal war machines, and demon legions in blackened bronze without end.",
"draenei": "Tall, blue-to-lavender skinned exiles with cranial crests, tendrils, tails, and hooves, their cities grown from glowing pink-white crystal.",
"dracthyr": "Slender humanoid dragons — scaled, winged, mailed in their own hide — who can fold themselves into unassuming elf-like 'visage' forms.",
"dragonflights": "Five colors on the wind: ruby, emerald, bronze, sapphire, and obsidian, each flight bearing its Aspect's charge.",
"elemental-lords": "Four living cataclysms: a firelord of magma and rage, a wind-prince of storm, a stone tyrant, and a tide-queen.",
"eredar": "The template the word 'demon' now brings to mind — horned, hooved, tailed magi of terrible elegance, in crimson and grey-blue.",
"forsaken": "The free-willed dead: grey flesh, glowing amber eyes, bone showing at the joints, banners of tattered violet.",
"horde": "Banners of red and black; spiked iron, wolf totems, drums.",
"mortal-races": "Stocky mountain-folk, small ingenious tinkerers, and adaptable plains-and-castle humans — flesh where their ancestors were stone and steel.",
"naaru": "Beings of pure Light: floating, chiming constellations of golden crystal shards, wordless and warm.",
"naga": "Sea-serpents with torsos and arms — finned, scaled, trident-armed — the drowned court remade for the deep.",
"night-elves": "Violet-skinned, silver- or amber-eyed elves of towering height, at home in moonlit old-growth forest; their cities grow rather than stand.",
"old-gods": "Mountains of eyes, maws, and tentacle wreathed in whisper — flesh that should not be, at planetary scale.",
"orcs": "Massive tusked warriors — born brown-skinned; the fel blood of their corruption turned the race green.",
"pandaren": "Black-and-white bear-folk of unhurried good humor, brewers and monks in a landscape of jade and mist.",
"primalists": "Elemental zealots in storm-, flame-, frost-, and stone-wrought armor, and the proto-dragons who lead them.",
"scourge": "A tide of the walking dead — skeletal soldiers, patchwork abominations, frost wyrms of bare bone — under a plague-green sky.",
"tauren": "Towering bison-folk with great horns and gentle voices, dwelling in painted hide tents on golden plains.",
"titanforged": "Warriors of animate stone and metal — some like giants of granite, the keepers like demigods of bronze and silver.",
"titans": "Beings the size of moons: living metal and stone, star-fields for eyes, worlds for cradles.",
"trolls": "Tall, wiry, tusked, and long-eared, in totemic empires of stone ziggurats — blue-skinned in the jungles, forest-green in the woods, sand-hued in the deserts.",
"void-lords": "Never truly seen: presences of hungering shadow at the edge of reality, known only by their weapons and their whispers.",
"wild-gods": "Beast-spirits at demigod scale — a moon-white tiger, a great bear, a raven that is also a storm — wreathed in the Dream's green light.",

# Places & Realms
"argus": "A scarred sphere of fel-green fire and shattered crust, hanging in Azeroth's sky like an accusing eye during the Legion's last war.",
"azeroth": "Seen from above: a blue-green world of two great continents flanking a storm-wracked central sea — and, at its molten heart, a sleeping god.",
"black-temple": "A fortress-temple of green-black stone in Outland's ash wastes, its draenei grace buried under demon iron.",
"dark-portal": "A colossal free-standing gateway of green-lit black stone, flanked by hooded statues, its interior a sheet of boiling emerald void.",
"dragon-isles": "A hidden subcontinent of primeval valleys, titan spires, and waterfalls the height of mountains, lit as if the world were still new.",
"eastern-kingdoms": "A north-south chain of kingdoms: golden elf-forests at the crown, plagued heartlands, dwarven snow-peaks, and Stormwind's green south.",
"emerald-dream": "Azeroth as it would be without mortals: the same world, endless-green, dreaming — its sky aurora'd, its forests vast beyond age.",
"icecrown": "A black saronite spire rising from a glacier, ringed by walls of ice and the frozen dead — visible for miles, warm nowhere.",
"kalimdor": "The wilder western continent: moonlit elf forests in the north, golden savannas and red desert canyons in the south.",
"lordaeron": "Once white-stone towns and autumn fields under cathedral bells; now the Plaguelands — sick ochre earth, blighted air, and the ruined capital's silent throne.",
"nordrassil": "A World Tree crowning Mount Hyjal's snow-peak, its canopy in the clouds, the scarred well glimmering among its roots.",
"northrend": "The frozen crown of the world: glacier coasts, howling tundra, and the green-lit vaults of dead empires beneath.",
"orgrimmar": "A fortress-city of red desert rock, dark iron, and spiked palisades, banners snapping in canyon wind.",
"outland": "The shattered corpse of Draenor: floating islands over an endless nether-sky, red wastes, fungal marsh, and one impossible green valley.",
"pandaria": "Jade forests, terraced emerald valleys, and cloud-wrapped peaks — a continent like a landscape painting, with something dark sealed under the floorboards.",
"quelthalas": "A kingdom of eternal autumn: gold-leafed forests threaded with white-and-gold spires, warm long after sunset.",
"shadowlands": "The afterlife as cosmos: a shattered sky of realms — gold-winged Bastion, autumnal Ardenweald, gothic Revendreth — all orbiting the screaming pit of the Maw.",
"silithus": "A wind-scoured southern desert of hives and ruins — now dominated by a continent-sized sword standing hilt-to-heaven in a wound of gold.",
"stormwind": "A proud human city of white stone and blue slate roofs, canals and cathedral square, rebuilt stone by stone after its fall.",
"sunwell": "A fount of liquid gold light in a white-and-gold sanctum at Quel'Thalas's northern isle — less a place than a heartbeat.",
"teldrassil": "A World Tree grown into an island: an entire night elf civilization in its boughs, purple-canopied, moon-silvered — before the fire.",
"ulduar": "A titan city of bronze, stone, and snow in Northrend's peaks — half temple, half machine, its vaults humming over a prison.",
"vault-incarnates": "A titan-built prison sunk in a storm-wracked crag of the Isles: rings of ordered stone and arcane seals around four cells of elemental fury.",
"well-of-eternity": "An inland sea of silver-gold starlight at the heart of the old world, its surface currents moving like slow galaxies.",

# Artifacts & Substances
"azerite": "Veins and boulders of glowing amber-gold crystal — warm, faintly pulsing, unmistakably alive.",
"demon-soul": "A featureless disc of perfect gold, small enough to palm, heavy with the essence of four dragonflights.",
"frostmourne": "A long pale runeblade, fuller etched with burning blue runes, a horned skull at the guard — cold that hungers.",
"heart-yshaarj": "A house-sized black heart, still beating after ten thousand years, veined in sha-white.",
"helm": "A jagged crown-helm of dark saronite, ice-blue light burning through its eye slits even when no one wears it.",
"sword-sargeras": "A blade of blackened metal the height of a mountain range, driven to the hilt into the desert of Silithus, wound-light glowing at its base.",
}

# warcraft.wiki.gg article for each entry (the page's infobox art is the visual reference).
WIKI = {
"aegwynn": W+"Aegwynn", "alexstrasza": W+"Alexstrasza", "amanthul": W+"Aman%27Thul",
"anduin": W+"Anduin_Wrynn", "archimonde": W+"Archimonde", "arthas": W+"Arthas_Menethil",
"azshara": W+"Queen_Azshara", "bolvar": W+"Bolvar_Fordragon", "cenarius": W+"Cenarius",
"cthun": W+"C%27Thun", "ebyssian": W+"Ebyssian", "fyrakk": W+"Fyrakk",
"galakrond": W+"Galakrond", "garrosh": W+"Garrosh_Hellscream", "grommash": W+"Grommash_Hellscream",
"guldan": W+"Gul%27dan", "guardian": W+"Guardian_of_Tirisfal", "illidan": W+"Illidan_Stormrage",
"iridikron": W+"Iridikron", "jaina": W+"Jaina_Proudmoore", "kaelthas": W+"Kael%27thas_Sunstrider",
"kalecgos": W+"Kalecgos", "kelthuzad": W+"Kel%27Thuzad", "khadgar": W+"Khadgar",
"kiljaeden": W+"Kil%27jaeden", "lich-king": W+"Lich_King", "lothar": W+"Anduin_Lothar",
"malfurion": W+"Malfurion_Stormrage", "malygos": W+"Malygos", "mannoroth": W+"Mannoroth",
"medivh": W+"Medivh", "merithra": W+"Merithra", "murozond": W+"Murozond",
"neltharion": W+"Deathwing", "nerzhul": W+"Ner%27zhul", "nozdormu": W+"Nozdormu",
"nzoth": W+"N%27Zoth", "odyn": W+"Odyn", "raszageth": W+"Raszageth",
"sabellian": W+"Sabellian", "sargeras": W+"Sargeras", "sylvanas": W+"Sylvanas_Windrunner",
"thrall": W+"Thrall", "turalyon": W+"Turalyon", "tyr": W+"Tyr",
"tyrande": W+"Tyrande_Whisperwind", "uther": W+"Uther_the_Lightbringer", "varian": W+"Varian_Wrynn",
"vashj": W+"Lady_Vashj", "velen": W+"Velen", "voljin": W+"Vol%27jin",
"vyranoth": W+"Vyranoth", "wrathion": W+"Wrathion", "xavius": W+"Xavius",
"yoggsaron": W+"Yogg-Saron", "ysera": W+"Ysera", "yshaarj": W+"Y%27Shaarj",
"zovaal": W+"Zovaal",
"alliance": W+"Alliance", "blood-elves": W+"Blood_elf", "burning-legion": W+"Burning_Legion",
"draenei": W+"Draenei", "dracthyr": W+"Dracthyr", "dragonflights": W+"Dragonflight_(dragon)",
"elemental-lords": W+"Elemental_Lord", "eredar": W+"Eredar", "forsaken": W+"Forsaken",
"horde": W+"Horde", "mortal-races": W+"Curse_of_flesh", "naaru": W+"Naaru",
"naga": W+"Naga", "night-elves": W+"Night_elf", "old-gods": W+"Old_Gods",
"orcs": W+"Orc", "pandaren": W+"Pandaren", "primalists": W+"Primalists",
"scourge": W+"Scourge", "tauren": W+"Tauren", "titanforged": W+"Titan-forged",
"titans": W+"Titan", "trolls": W+"Troll", "void-lords": W+"Void_lord",
"wild-gods": W+"Wild_God",
"argus": W+"Argus", "azeroth": W+"Azeroth", "black-temple": W+"Black_Temple",
"dark-portal": W+"Dark_Portal", "dragon-isles": W+"Dragon_Isles", "eastern-kingdoms": W+"Eastern_Kingdoms",
"emerald-dream": W+"Emerald_Dream", "icecrown": W+"Icecrown_Citadel", "kalimdor": W+"Kalimdor",
"lordaeron": W+"Lordaeron", "nordrassil": W+"Nordrassil", "northrend": W+"Northrend",
"orgrimmar": W+"Orgrimmar", "outland": W+"Outland", "pandaria": W+"Pandaria",
"quelthalas": W+"Quel%27Thalas", "shadowlands": W+"Shadowlands", "silithus": W+"Silithus",
"stormwind": W+"Stormwind_City", "sunwell": W+"Sunwell", "teldrassil": W+"Teldrassil",
"ulduar": W+"Ulduar", "vault-incarnates": W+"Vault_of_the_Incarnates", "well-of-eternity": W+"Well_of_Eternity",
"azerite": W+"Azerite", "demon-soul": W+"Demon_Soul", "frostmourne": W+"Frostmourne",
"heart-yshaarj": W+"Heart_of_Y%27Shaarj", "helm": W+"Helm_of_Domination", "sword-sargeras": W+"Sword_of_Sargeras",
"aspect": W+"Dragon_Aspects", "curse-of-flesh": W+"Curse_of_flesh", "sha": W+"Sha",
"sundering": W+"Great_Sundering", "world-soul": W+"World-soul",
}
